import type { ExerciseKind, ExerciseMuscle } from '../src/exercise'

// Aliases are true synonyms, abbreviations and alternate names only. The
// matcher (16b) normalizes case, punctuation and plurals, so "push ups",
// "push-ups" and "pushup" don't all need listing next to "push-up".

type CuratedBase = {
  name: string
  aliases?: readonly string[]
}

// Mapped to a free-exercise-db id; kind and muscles come from the source.
export type SourcedExercise = CuratedBase & {
  source: string
  kind?: ExerciseKind
}

// Not in free-exercise-db, so kind and muscles are written here; no photo.
export type HandwrittenExercise = CuratedBase & {
  kind: ExerciseKind
  primary: readonly ExerciseMuscle[]
  secondary?: readonly ExerciseMuscle[]
}

export type CuratedExercise = SourcedExercise | HandwrittenExercise

export const CURATED_EXERCISES: readonly CuratedExercise[] = [
  // Chest
  {
    name: 'bench press',
    source: 'Barbell_Bench_Press_-_Medium_Grip',
    aliases: ['barbell bench press', 'flat bench press', 'bench', 'bb bench'],
  },
  {
    name: 'incline bench press',
    source: 'Barbell_Incline_Bench_Press_-_Medium_Grip',
    aliases: ['incline bench', 'incline barbell press'],
  },
  {
    name: 'decline bench press',
    source: 'Decline_Barbell_Bench_Press',
    aliases: [
      'decline bench',
      'decline barbell press',
      'decline dumbbell press',
    ],
  },
  {
    name: 'close grip bench press',
    source: 'Close-Grip_Barbell_Bench_Press',
    aliases: ['close grip bench', 'cgbp'],
  },
  {
    name: 'dumbbell bench press',
    source: 'Dumbbell_Bench_Press',
    aliases: [
      'db bench press',
      'dumbbell press',
      'dumbbell chest press',
      'db bench',
      'flat dumbbell press',
    ],
  },
  {
    name: 'incline dumbbell press',
    source: 'Incline_Dumbbell_Press',
    aliases: ['incline db press', 'incline dumbbell bench press'],
  },
  {
    name: 'chest press',
    source: 'Leverage_Chest_Press',
    aliases: [
      'machine chest press',
      'chest press machine',
      'seated chest press',
    ],
  },
  {
    name: 'smith machine bench press',
    source: 'Smith_Machine_Bench_Press',
    aliases: ['smith bench press', 'smith press'],
  },
  {
    name: 'push-up',
    source: 'Pushups',
    aliases: ['pushup', 'press-up', 'pressup'],
  },
  {
    name: 'wide push-up',
    source: 'Push-Up_Wide',
    aliases: ['wide pushup', 'wide grip push-up'],
  },
  {
    name: 'diamond push-up',
    source: 'Push-Ups_-_Close_Triceps_Position',
    aliases: ['diamond pushup', 'close grip push-up', 'triceps push-up'],
  },
  {
    name: 'incline push-up',
    source: 'Incline_Push-Up',
    aliases: ['incline pushup'],
  },
  {
    name: 'decline push-up',
    source: 'Decline_Push-Up',
    aliases: ['decline pushup', 'feet elevated push-up'],
  },
  {
    name: 'plyo push-up',
    source: 'Plyo_Push-up',
    aliases: [
      'plyo pushup',
      'clap push-up',
      'clap pushup',
      'explosive push-up',
    ],
  },
  {
    name: 'wall push-up',
    kind: 'strength',
    primary: ['chest'],
    secondary: ['shoulders', 'triceps'],
    aliases: ['wall pushup'],
  },
  {
    name: 'knee push-up',
    kind: 'strength',
    primary: ['chest'],
    secondary: ['shoulders', 'triceps'],
    aliases: ['knee pushup', 'kneeling push-up', 'kneeling pushup'],
  },
  {
    name: 'pike push-up',
    kind: 'strength',
    primary: ['shoulders'],
    secondary: ['triceps', 'chest'],
    aliases: ['pike pushup', 'pike press'],
  },
  {
    name: 'dumbbell fly',
    source: 'Dumbbell_Flyes',
    aliases: [
      'dumbbell flye',
      'chest fly',
      'chest flye',
      'db fly',
      'fly',
      'flye',
    ],
  },
  {
    name: 'incline dumbbell fly',
    source: 'Incline_Dumbbell_Flyes',
    aliases: ['incline fly', 'incline flye', 'incline db fly'],
  },
  {
    name: 'cable crossover',
    source: 'Cable_Crossover',
    aliases: ['cable fly', 'cable flye', 'cable chest fly'],
  },
  {
    name: 'pec deck',
    source: 'Butterfly',
    aliases: [
      'pec dec',
      'butterfly machine',
      'machine fly',
      'chest fly machine',
      'pec fly',
    ],
  },
  {
    name: 'dumbbell pullover',
    source: 'Straight-Arm_Dumbbell_Pullover',
    aliases: ['pullover', 'db pullover'],
  },

  // Back
  {
    name: 'pull-up',
    source: 'Pullups',
    aliases: ['pullup', 'wide grip pull-up', 'wide grip pullup'],
  },
  { name: 'chin-up', source: 'Chin-Up', aliases: ['chinup'] },
  {
    name: 'assisted pull-up',
    source: 'Band_Assisted_Pull-Up',
    aliases: ['assisted pullup', 'band assisted pull-up', 'banded pull-up'],
  },
  { name: 'muscle-up', source: 'Muscle_Up', aliases: ['muscleup'] },
  {
    name: 'lat pulldown',
    source: 'Wide-Grip_Lat_Pulldown',
    aliases: [
      'lat pull down',
      'pulldown',
      'pull down',
      'wide grip lat pulldown',
      'wide grip pulldown',
    ],
  },
  {
    name: 'close grip lat pulldown',
    source: 'Close-Grip_Front_Lat_Pulldown',
    aliases: ['close grip pulldown', 'narrow grip pulldown'],
  },
  {
    name: 'underhand lat pulldown',
    source: 'Underhand_Cable_Pulldowns',
    aliases: [
      'underhand pulldown',
      'reverse grip pulldown',
      'reverse grip lat pulldown',
    ],
  },
  {
    name: 'straight arm pulldown',
    source: 'Straight-Arm_Pulldown',
    aliases: ['straight arm pull down', 'straight arm lat pulldown'],
  },
  {
    name: 'barbell row',
    source: 'Bent_Over_Barbell_Row',
    aliases: ['bent over row', 'bent over barbell row', 'bb row'],
  },
  {
    name: 'dumbbell row',
    source: 'One-Arm_Dumbbell_Row',
    aliases: [
      'one arm dumbbell row',
      'single arm dumbbell row',
      'single arm row',
      'one arm row',
      'db row',
    ],
  },
  {
    name: 'chest supported row',
    source: 'Dumbbell_Incline_Row',
    aliases: ['incline dumbbell row', 'incline bench row', 'prone row'],
  },
  {
    name: 'seated cable row',
    source: 'Seated_Cable_Rows',
    aliases: [
      'cable row',
      'seated row',
      'low row',
      'machine row',
      'iso row',
      'hammer strength row',
    ],
  },
  { name: 't-bar row', source: 'T-Bar_Row_with_Handle', aliases: ['tbar row'] },
  {
    name: 'inverted row',
    source: 'Inverted_Row',
    aliases: [
      'australian pull-up',
      'australian pullup',
      'bodyweight row',
      'body row',
    ],
  },
  {
    name: 'trx row',
    source: 'Suspended_Row',
    aliases: ['suspension row', 'suspended row', 'ring row'],
  },
  {
    name: 'renegade row',
    source: 'Alternating_Renegade_Row',
    aliases: ['plank row'],
  },
  {
    name: 'kettlebell row',
    source: 'One-Arm_Kettlebell_Row',
    aliases: ['kb row', 'one arm kettlebell row'],
  },
  {
    name: 'face pull',
    source: 'Face_Pull',
    aliases: ['cable face pull', 'rope face pull'],
  },
  {
    name: 'shrug',
    source: 'Barbell_Shrug',
    aliases: ['barbell shrug', 'bb shrug', 'dumbbell shrug', 'db shrug'],
  },
  {
    name: 'deadlift',
    source: 'Barbell_Deadlift',
    aliases: ['conventional deadlift', 'barbell deadlift', 'dl', 'dead lift'],
  },
  {
    name: 'romanian deadlift',
    source: 'Romanian_Deadlift',
    aliases: [
      'rdl',
      'barbell rdl',
      'stiff leg deadlift',
      'stiff legged deadlift',
      'sldl',
    ],
  },
  {
    name: 'dumbbell romanian deadlift',
    source: 'Stiff-Legged_Dumbbell_Deadlift',
    aliases: ['dumbbell rdl', 'db rdl', 'dumbbell stiff leg deadlift'],
  },
  { name: 'sumo deadlift', source: 'Sumo_Deadlift', aliases: ['sumo dl'] },
  {
    name: 'trap bar deadlift',
    source: 'Trap_Bar_Deadlift',
    aliases: ['hex bar deadlift'],
  },
  {
    name: 'single leg deadlift',
    source: 'Kettlebell_One-Legged_Deadlift',
    aliases: ['one leg deadlift', 'one legged deadlift', 'single leg rdl'],
  },
  {
    name: 'dumbbell deadlift',
    kind: 'strength',
    primary: ['hamstrings'],
    secondary: ['glutes', 'lower back', 'quadriceps', 'forearms'],
    aliases: ['db deadlift', 'kettlebell deadlift', 'kb deadlift'],
  },
  {
    name: 'good morning',
    source: 'Good_Morning',
    aliases: ['barbell good morning'],
  },
  {
    name: 'back extension',
    source: 'Hyperextensions_Back_Extensions',
    aliases: ['hyperextension', 'hyper extension', '45 degree back extension'],
  },
  {
    name: 'superman',
    source: 'Superman',
    kind: 'strength',
    aliases: ['superman raise'],
  },
  {
    name: 'pull-through',
    source: 'Pull_Through',
    aliases: ['cable pull through'],
  },

  // Shoulders
  {
    name: 'overhead press',
    source: 'Standing_Military_Press',
    aliases: [
      'ohp',
      'military press',
      'barbell overhead press',
      'standing barbell press',
      'barbell shoulder press',
      'barbell press',
      'strict press',
      'seated overhead press',
    ],
  },
  {
    name: 'dumbbell shoulder press',
    source: 'Dumbbell_Shoulder_Press',
    aliases: [
      'shoulder press',
      'dumbbell overhead press',
      'db shoulder press',
      'db press',
      'seated dumbbell press',
      'dumbbell military press',
      'kettlebell press',
      'kb press',
    ],
  },
  { name: 'arnold press', source: 'Arnold_Dumbbell_Press' },
  {
    name: 'machine shoulder press',
    source: 'Machine_Shoulder_Military_Press',
    aliases: ['shoulder press machine', 'smith machine shoulder press'],
  },
  { name: 'push press', source: 'Push_Press', aliases: ['barbell push press'] },
  {
    name: 'lateral raise',
    source: 'Side_Lateral_Raise',
    aliases: [
      'side lateral raise',
      'side raise',
      'dumbbell lateral raise',
      'db lateral raise',
      'lat raise',
      'side lateral',
    ],
  },
  {
    name: 'front raise',
    source: 'Front_Dumbbell_Raise',
    aliases: [
      'dumbbell front raise',
      'db front raise',
      'plate front raise',
      'plate raise',
    ],
  },
  {
    name: 'rear delt fly',
    source: 'Reverse_Flyes',
    aliases: [
      'rear delt flye',
      'reverse fly',
      'reverse flye',
      'rear delt raise',
      'bent over lateral raise',
      'cable rear delt fly',
      'reverse pec deck',
      'rear delt machine',
    ],
  },
  {
    name: 'upright row',
    source: 'Upright_Barbell_Row',
    aliases: ['barbell upright row', 'dumbbell upright row', 'db upright row'],
  },
  {
    name: 'band pull apart',
    source: 'Band_Pull_Apart',
    aliases: ['pull apart', 'banded pull apart'],
  },
  {
    name: 'external rotation',
    source: 'External_Rotation',
    aliases: [
      'shoulder external rotation',
      'dumbbell external rotation',
      'band external rotation',
      'cable external rotation',
    ],
  },
  {
    name: 'handstand push-up',
    source: 'Handstand_Push-Ups',
    aliases: ['handstand pushup', 'hspu'],
  },
  {
    name: 'kettlebell halo',
    source: 'Kettlebell_Halo',
    aliases: ['halo', 'kb halo'],
  },
  {
    name: 'battle ropes',
    source: 'Battling_Ropes',
    aliases: ['battling ropes', 'rope slam', 'battle rope wave'],
  },
  {
    name: 'arm circles',
    source: 'Arm_Circles',
    kind: 'strength',
    aliases: ['arm rotation', 'shoulder circles', 'arm swings'],
  },

  // Biceps
  {
    name: 'bicep curl',
    source: 'Dumbbell_Bicep_Curl',
    aliases: [
      'dumbbell curl',
      'db curl',
      'dumbbell bicep curl',
      'curl',
      'arm curl',
      'alternating dumbbell curl',
      'alternating curl',
      'alternating bicep curl',
    ],
  },
  {
    name: 'barbell curl',
    source: 'Barbell_Curl',
    aliases: ['bb curl', 'barbell bicep curl'],
  },
  { name: 'ez bar curl', source: 'EZ-Bar_Curl', aliases: ['ez curl'] },
  {
    name: 'hammer curl',
    source: 'Hammer_Curls',
    aliases: [
      'dumbbell hammer curl',
      'db hammer curl',
      'rope hammer curl',
      'cable hammer curl',
    ],
  },
  {
    name: 'incline dumbbell curl',
    source: 'Incline_Dumbbell_Curl',
    aliases: ['incline curl', 'incline db curl'],
  },
  {
    name: 'preacher curl',
    source: 'Preacher_Curl',
    aliases: [
      'barbell preacher curl',
      'ez bar preacher curl',
      'machine preacher curl',
      'preacher curl machine',
    ],
  },
  { name: 'concentration curl', source: 'Concentration_Curls' },
  {
    name: 'cable curl',
    source: 'Standing_Biceps_Cable_Curl',
    aliases: ['cable bicep curl', 'low pulley curl'],
  },
  {
    name: 'reverse curl',
    source: 'Reverse_Barbell_Curl',
    aliases: [
      'reverse barbell curl',
      'reverse grip curl',
      'pronated curl',
      'overhand curl',
    ],
  },

  // Triceps
  {
    name: 'dip',
    source: 'Dips_-_Triceps_Version',
    aliases: [
      'tricep dip',
      'parallel bar dip',
      'bar dip',
      'chest dip',
      'ring dip',
      'machine dip',
      'assisted dip',
    ],
  },
  {
    name: 'bench dip',
    source: 'Bench_Dips',
    aliases: ['tricep bench dip', 'chair dip'],
  },
  {
    name: 'tricep pushdown',
    source: 'Triceps_Pushdown',
    aliases: [
      'cable pushdown',
      'pushdown',
      'tricep push down',
      'cable tricep pushdown',
      'straight bar pushdown',
      'v-bar pushdown',
    ],
  },
  {
    name: 'rope pushdown',
    source: 'Triceps_Pushdown_-_Rope_Attachment',
    aliases: [
      'rope tricep pushdown',
      'tricep rope pushdown',
      'rope tricep extension',
    ],
  },
  {
    name: 'skull crusher',
    source: 'EZ-Bar_Skullcrusher',
    aliases: [
      'skullcrusher',
      'lying tricep extension',
      'ez bar skull crusher',
      'french press',
    ],
  },
  {
    name: 'overhead tricep extension',
    source: 'Standing_Dumbbell_Triceps_Extension',
    aliases: [
      'tricep extension',
      'dumbbell tricep extension',
      'db tricep extension',
      'overhead dumbbell extension',
      'overhead extension',
    ],
  },
  {
    name: 'cable overhead tricep extension',
    source: 'Triceps_Overhead_Extension_with_Rope',
    aliases: [
      'rope overhead extension',
      'rope overhead tricep extension',
      'overhead rope extension',
      'overhead cable extension',
    ],
  },
  {
    name: 'tricep kickback',
    source: 'Tricep_Dumbbell_Kickback',
    aliases: ['dumbbell kickback', 'db kickback'],
  },

  // Forearms and grip
  {
    name: 'wrist curl',
    source: 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench',
    aliases: ['barbell wrist curl', 'forearm curl', 'reverse wrist curl'],
  },
  {
    name: "farmer's walk",
    source: 'Farmers_Walk',
    kind: 'hold',
    aliases: [
      'farmer walk',
      "farmer's carry",
      'farmer carry',
      'farmers carry',
      'loaded carry',
    ],
  },
  {
    name: 'dead hang',
    kind: 'hold',
    primary: ['forearms'],
    secondary: ['lats', 'shoulders'],
    aliases: ['bar hang', 'hang from bar', 'passive hang'],
  },

  // Quads
  {
    name: 'squat',
    source: 'Barbell_Squat',
    aliases: [
      'back squat',
      'barbell squat',
      'barbell back squat',
      'bb squat',
      'high bar squat',
      'low bar squat',
      'box squat',
      'smith machine squat',
      'smith squat',
    ],
  },
  {
    name: 'front squat',
    source: 'Front_Barbell_Squat',
    aliases: ['barbell front squat'],
  },
  {
    name: 'bodyweight squat',
    source: 'Bodyweight_Squat',
    aliases: ['body weight squat', 'air squat', 'bw squat', 'free squat'],
  },
  {
    name: 'goblet squat',
    source: 'Goblet_Squat',
    aliases: [
      'kettlebell goblet squat',
      'kb goblet squat',
      'dumbbell goblet squat',
      'dumbbell squat',
      'db squat',
    ],
  },
  {
    name: 'hack squat',
    source: 'Hack_Squat',
    aliases: ['hack squat machine'],
  },
  { name: 'overhead squat', source: 'Overhead_Squat', aliases: ['ohs'] },
  {
    name: 'sumo squat',
    source: 'Plie_Dumbbell_Squat',
    aliases: ['plie squat', 'plié squat', 'wide stance squat', 'wide squat'],
  },
  {
    name: 'pistol squat',
    source: 'Kettlebell_Pistol_Squat',
    aliases: [
      'pistol',
      'single leg squat',
      'one leg squat',
      'one legged squat',
    ],
  },
  {
    name: 'jump squat',
    source: 'Freehand_Jump_Squat',
    aliases: ['squat jump', 'jumping squat'],
  },
  {
    name: 'split squat',
    source: 'Split_Squat_with_Dumbbells',
    aliases: ['dumbbell split squat', 'static lunge'],
  },
  {
    name: 'bulgarian split squat',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['glutes', 'hamstrings', 'calves'],
    aliases: [
      'bulgarian squat',
      'bulgarian',
      'rear foot elevated split squat',
      'rfess',
    ],
  },
  {
    name: 'cossack squat',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['adductors', 'glutes', 'hamstrings'],
    aliases: ['cossack'],
  },
  {
    name: 'squat hold',
    kind: 'hold',
    primary: ['quadriceps'],
    secondary: ['glutes', 'hamstrings'],
    aliases: [
      'deep squat hold',
      'isometric squat',
      'iso squat',
      'static squat',
    ],
  },
  {
    name: 'wall sit',
    kind: 'hold',
    primary: ['quadriceps'],
    secondary: ['glutes', 'calves'],
    aliases: ['wall squat', 'wall squat hold', 'wall chair', 'wall sit hold'],
  },
  {
    name: 'lunge',
    source: 'Dumbbell_Lunges',
    aliases: [
      'forward lunge',
      'dumbbell lunge',
      'db lunge',
      'stationary lunge',
      'front lunge',
      'alternating lunge',
      'barbell lunge',
    ],
  },
  {
    name: 'walking lunge',
    source: 'Bodyweight_Walking_Lunge',
    aliases: ['lunge walk'],
  },
  {
    name: 'reverse lunge',
    source: 'Dumbbell_Rear_Lunge',
    aliases: ['rear lunge', 'backward lunge', 'back lunge', 'step back lunge'],
  },
  {
    name: 'lateral lunge',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['adductors', 'glutes', 'hamstrings'],
    aliases: ['side lunge', 'sideways lunge'],
  },
  {
    name: 'curtsy lunge',
    kind: 'strength',
    primary: ['glutes'],
    secondary: ['quadriceps', 'adductors', 'hamstrings'],
    aliases: ['curtsey lunge', 'curtsy squat'],
  },
  {
    name: 'split jump',
    source: 'Split_Jump',
    aliases: [
      'jump lunge',
      'jumping lunge',
      'lunge jump',
      'plyo lunge',
      'switch lunge',
    ],
  },
  {
    name: 'step-up',
    source: 'Dumbbell_Step_Ups',
    aliases: ['stepup', 'box step-up', 'dumbbell step-up', 'bench step-up'],
  },
  {
    name: 'leg press',
    source: 'Leg_Press',
    aliases: ['leg press machine', 'seated leg press'],
  },
  {
    name: 'leg extension',
    source: 'Leg_Extensions',
    aliases: ['quad extension', 'leg extension machine', 'knee extension'],
  },
  {
    name: 'sled push',
    source: 'Sled_Push',
    aliases: [
      'prowler push',
      'prowler',
      'sled sprint',
      'sled drag',
      'sled pull',
    ],
  },
  {
    name: 'box jump',
    source: 'Front_Box_Jump',
    aliases: ['tuck jump', 'knee tuck jump'],
  },
  {
    name: 'broad jump',
    source: 'Standing_Long_Jump',
    aliases: ['standing long jump', 'long jump', 'standing broad jump'],
  },
  {
    name: 'skater jump',
    source: 'Lateral_Bound',
    aliases: ['lateral bound', 'skater hop', 'speed skater', 'lateral hop'],
  },

  // Hamstrings and glutes
  {
    name: 'leg curl',
    source: 'Lying_Leg_Curls',
    aliases: [
      'lying leg curl',
      'hamstring curl',
      'lying hamstring curl',
      'leg curl machine',
      'prone leg curl',
    ],
  },
  {
    name: 'seated leg curl',
    source: 'Seated_Leg_Curl',
    aliases: ['seated hamstring curl'],
  },
  {
    name: 'nordic curl',
    source: 'Natural_Glute_Ham_Raise',
    aliases: [
      'nordic hamstring curl',
      'nordic',
      'natural glute ham raise',
      'nordic ham curl',
    ],
  },
  {
    name: 'glute ham raise',
    source: 'Glute_Ham_Raise',
    aliases: ['ghr', 'ghd', 'glute ham developer'],
  },
  {
    name: 'swiss ball leg curl',
    source: 'Ball_Leg_Curl',
    aliases: [
      'stability ball leg curl',
      'exercise ball leg curl',
      'ball leg curl',
      'swiss ball hamstring curl',
    ],
  },
  {
    name: 'hip thrust',
    source: 'Barbell_Hip_Thrust',
    aliases: [
      'barbell hip thrust',
      'weighted hip thrust',
      'hip thruster',
      'barbell glute bridge',
      'weighted glute bridge',
    ],
  },
  {
    name: 'glute bridge',
    source: 'Butt_Lift_Bridge',
    aliases: [
      'bridge',
      'hip bridge',
      'floor bridge',
      'butt lift',
      'single leg glute bridge',
      'single leg bridge',
      'one leg glute bridge',
    ],
  },
  {
    name: 'glute kickback',
    source: 'Glute_Kickback',
    aliases: [
      'donkey kick',
      'quadruped hip extension',
      'kneeling kickback',
      'cable glute kickback',
    ],
  },
  {
    name: 'kettlebell swing',
    source: 'One-Arm_Kettlebell_Swings',
    aliases: [
      'kb swing',
      'russian swing',
      'russian kettlebell swing',
      'one arm kettlebell swing',
      'swing',
    ],
  },
  {
    name: 'hip abduction',
    source: 'Thigh_Abductor',
    aliases: [
      'abductor machine',
      'abduction machine',
      'hip abductor',
      'hip abductor machine',
      'seated abduction',
    ],
  },
  {
    name: 'hip adduction',
    source: 'Thigh_Adductor',
    aliases: [
      'adductor machine',
      'adduction machine',
      'hip adductor',
      'hip adductor machine',
      'seated adduction',
      'inner thigh machine',
    ],
  },
  {
    name: 'monster walk',
    source: 'Monster_Walk',
    aliases: [
      'banded monster walk',
      'band walk',
      'banded walk',
      'lateral band walk',
      'side band walk',
    ],
  },
  {
    name: 'clamshell',
    kind: 'strength',
    primary: ['glutes'],
    secondary: ['abductors'],
    aliases: ['clam shell', 'clam', 'banded clamshell', 'side lying clam'],
  },
  {
    name: 'fire hydrant',
    kind: 'strength',
    primary: ['glutes'],
    secondary: ['abductors'],
    aliases: ['hydrant', 'quadruped hip abduction'],
  },
  {
    name: 'side leg raise',
    source: 'Side_Leg_Raises',
    kind: 'strength',
    aliases: [
      'side lying leg raise',
      'lying side leg raise',
      'lateral leg raise',
      'side lying hip abduction',
      'side leg lift',
    ],
  },
  {
    name: 'leg swings',
    source: 'Front_Leg_Raises',
    kind: 'strength',
    aliases: [
      'front leg swings',
      'front leg raises',
      'standing leg swings',
      'dynamic leg swings',
    ],
  },

  // Calves
  {
    name: 'calf raise',
    source: 'Standing_Calf_Raises',
    aliases: [
      'standing calf raise',
      'machine calf raise',
      'calf raise machine',
      'barbell calf raise',
      'smith machine calf raise',
      'donkey calf raise',
    ],
  },
  {
    name: 'seated calf raise',
    source: 'Seated_Calf_Raise',
    aliases: ['seated calf raise machine'],
  },
  {
    name: 'dumbbell calf raise',
    source: 'Standing_Dumbbell_Calf_Raise',
    aliases: ['db calf raise', 'standing dumbbell calf raise'],
  },
  {
    name: 'single leg calf raise',
    kind: 'strength',
    primary: ['calves'],
    aliases: ['one leg calf raise', 'one legged calf raise'],
  },
  {
    name: 'leg press calf raise',
    source: 'Calf_Press_On_The_Leg_Press_Machine',
    aliases: ['calf press', 'calf press on leg press', 'leg press calves'],
  },

  // Core
  {
    name: 'plank',
    source: 'Plank',
    kind: 'hold',
    aliases: [
      'front plank',
      'forearm plank',
      'elbow plank',
      'high plank',
      'plank hold',
      'low plank',
    ],
  },
  {
    name: 'side plank',
    source: 'Side_Bridge',
    kind: 'hold',
    aliases: ['side bridge', 'side plank hold', 'lateral plank'],
  },
  {
    name: 'reverse plank',
    kind: 'hold',
    primary: ['glutes'],
    secondary: ['abdominals', 'hamstrings', 'shoulders'],
    aliases: ['back plank', 'supine plank'],
  },
  {
    name: 'plank shoulder taps',
    kind: 'strength',
    primary: ['abdominals'],
    secondary: ['shoulders'],
    aliases: ['shoulder taps', 'plank taps'],
  },
  {
    name: 'hollow hold',
    kind: 'hold',
    primary: ['abdominals'],
    aliases: ['hollow body hold', 'hollow body', 'hollow rock hold'],
  },
  {
    name: 'l-sit',
    kind: 'hold',
    primary: ['abdominals'],
    secondary: ['quadriceps', 'triceps', 'shoulders'],
    aliases: ['lsit', 'l-sit hold'],
  },
  {
    name: 'crunch',
    source: 'Crunches',
    aliases: [
      'ab crunch',
      'abdominal crunch',
      'floor crunch',
      'decline crunch',
      'decline sit-up',
    ],
  },
  { name: 'sit-up', source: 'Sit-Up', aliases: ['situp'] },
  {
    name: 'bicycle crunch',
    source: 'Air_Bike',
    aliases: ['bicycle kick', 'bicycle sit-up'],
  },
  {
    name: 'reverse crunch',
    source: 'Reverse_Crunch',
    aliases: ['reverse sit-up'],
  },
  {
    name: 'oblique crunch',
    source: 'Oblique_Crunches',
    aliases: [
      'side crunch',
      'oblique sit-up',
      'cross body crunch',
      'crossover crunch',
    ],
  },
  {
    name: 'cable crunch',
    source: 'Cable_Crunch',
    aliases: ['kneeling cable crunch', 'rope crunch', 'kneeling rope crunch'],
  },
  {
    name: 'machine crunch',
    source: 'Ab_Crunch_Machine',
    aliases: [
      'ab machine',
      'ab crunch machine',
      'crunch machine',
      'abdominal machine',
      'seated ab crunch',
    ],
  },
  {
    name: 'leg raise',
    source: 'Flat_Bench_Lying_Leg_Raise',
    aliases: [
      'lying leg raise',
      'leg lift',
      'lying leg lift',
      'floor leg raise',
      'straight leg raise',
      'supine leg raise',
    ],
  },
  {
    name: 'hanging leg raise',
    source: 'Hanging_Leg_Raise',
    aliases: ['hanging knee raise', 'hanging leg lift', 'hanging knee tuck'],
  },
  {
    name: 'knee raise',
    source: 'Knee_Hip_Raise_On_Parallel_Bars',
    aliases: [
      "captain's chair",
      "captain's chair knee raise",
      "captain's chair leg raise",
      'parallel bar knee raise',
      'dip bar knee raise',
      'vertical knee raise',
      'roman chair knee raise',
    ],
  },
  {
    name: 'toes to bar',
    kind: 'strength',
    primary: ['abdominals'],
    secondary: ['lats', 'forearms'],
    aliases: ['t2b', 'toe to bar'],
  },
  {
    name: 'russian twist',
    source: 'Russian_Twist',
    aliases: ['seated russian twist', 'weighted russian twist'],
  },
  {
    name: 'v-up',
    source: 'Jackknife_Sit-Up',
    aliases: [
      'vup',
      'jackknife',
      'jackknife sit-up',
      'jack knife',
      'v sit-up',
      'pike crunch',
    ],
  },
  {
    name: 'toe touch crunch',
    source: 'Toe_Touchers',
    kind: 'strength',
    aliases: ['toe toucher', 'lying toe touch', 'toe touch abs', 'toe reach'],
  },
  {
    name: 'flutter kick',
    source: 'Flutter_Kicks',
    aliases: ['flutter', 'lying flutter kick'],
  },
  {
    name: 'scissor kick',
    source: 'Scissor_Kick',
    kind: 'strength',
    aliases: ['scissor', 'leg scissors', 'scissors kick', 'scissor abs'],
  },
  { name: 'dead bug', source: 'Dead_Bug', aliases: ['deadbug'] },
  {
    name: 'bird dog',
    kind: 'strength',
    primary: ['lower back'],
    secondary: ['abdominals', 'glutes'],
    aliases: ['birddog', 'quadruped bird dog'],
  },
  {
    name: 'mountain climber',
    source: 'Mountain_Climbers',
    aliases: ['mtn climber', 'running plank'],
  },
  {
    name: 'bear crawl',
    kind: 'strength',
    primary: ['abdominals'],
    secondary: ['shoulders', 'quadriceps', 'triceps'],
    aliases: ['bear walk'],
  },
  {
    name: 'crab walk',
    kind: 'strength',
    primary: ['glutes'],
    secondary: ['triceps', 'shoulders', 'hamstrings'],
  },
  {
    name: 'inchworm',
    source: 'Inchworm',
    kind: 'strength',
    aliases: ['inch worm', 'inchworm walk'],
  },
  {
    name: 'ab wheel rollout',
    source: 'Ab_Roller',
    aliases: [
      'ab wheel',
      'ab roller',
      'ab rollout',
      'rollout',
      'wheel rollout',
      'kneeling rollout',
      'barbell rollout',
      'barbell ab rollout',
    ],
  },
  {
    name: 'pallof press',
    source: 'Pallof_Press',
    aliases: [
      'paloff press',
      'palloff press',
      'palof press',
      'cable pallof press',
      'band pallof press',
      'anti-rotation press',
    ],
  },
  {
    name: 'cable woodchop',
    source: 'Standing_Cable_Wood_Chop',
    aliases: [
      'woodchop',
      'wood chop',
      'cable wood chop',
      'woodchopper',
      'wood chopper',
      'cable chop',
    ],
  },
  {
    name: 'side bend',
    source: 'Dumbbell_Side_Bend',
    aliases: [
      'dumbbell side bend',
      'db side bend',
      'standing side bend',
      'weighted side bend',
      'oblique side bend',
    ],
  },
  {
    name: 'torso twist',
    kind: 'strength',
    primary: ['abdominals'],
    secondary: ['lower back'],
    aliases: [
      'trunk twist',
      'trunk rotation',
      'standing twist',
      'torso rotation',
      'waist twist',
    ],
  },
  {
    name: 'ball slam',
    source: 'Overhead_Slam',
    aliases: [
      'medicine ball slam',
      'med ball slam',
      'slam ball',
      'overhead slam',
      'overhead ball slam',
    ],
  },
  {
    name: 'turkish get-up',
    source: 'Kettlebell_Turkish_Get-Up_Squat_style',
    aliases: [
      'turkish getup',
      'tgu',
      'kettlebell turkish get-up',
      'get-up',
      'getup',
    ],
  },

  // Olympic lifts and full body
  {
    name: 'clean',
    source: 'Clean',
    aliases: ['squat clean', 'full clean', 'barbell clean'],
  },
  { name: 'power clean', source: 'Power_Clean' },
  { name: 'hang clean', source: 'Hang_Clean', aliases: ['hang power clean'] },
  {
    name: 'clean and jerk',
    source: 'Clean_and_Jerk',
    aliases: ['clean & jerk', 'c&j', 'c & j', 'cnj'],
  },
  {
    name: 'clean and press',
    source: 'Clean_and_Press',
    aliases: ['clean & press'],
  },
  {
    name: 'snatch',
    source: 'Snatch',
    aliases: ['squat snatch', 'full snatch', 'barbell snatch'],
  },
  {
    name: 'power snatch',
    source: 'Power_Snatch',
    aliases: ['hang snatch', 'hang power snatch'],
  },
  {
    name: 'split jerk',
    source: 'Split_Jerk',
    aliases: ['jerk', 'barbell jerk', 'push jerk', 'power jerk'],
  },
  {
    name: 'thruster',
    source: 'Kettlebell_Thruster',
    aliases: [
      'kettlebell thruster',
      'kb thruster',
      'barbell thruster',
      'dumbbell thruster',
      'db thruster',
      'squat to press',
      'squat press',
    ],
  },
  {
    name: 'kettlebell snatch',
    source: 'One-Arm_Kettlebell_Snatch',
    aliases: ['kb snatch', 'one arm kettlebell snatch'],
  },
  {
    name: 'kettlebell clean',
    source: 'One-Arm_Kettlebell_Clean',
    aliases: [
      'kb clean',
      'one arm kettlebell clean',
      'kettlebell clean and press',
      'kb clean and press',
      'kettlebell clean and jerk',
    ],
  },
  {
    name: 'dumbbell snatch',
    kind: 'strength',
    primary: ['shoulders'],
    secondary: ['hamstrings', 'glutes', 'quadriceps', 'traps'],
    aliases: [
      'db snatch',
      'single arm dumbbell snatch',
      'one arm dumbbell snatch',
      'alternating dumbbell snatch',
    ],
  },
  {
    name: 'burpee',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['chest', 'shoulders', 'triceps', 'abdominals', 'glutes'],
    aliases: ['burpie', 'burpee with push-up'],
  },
  {
    name: 'jumping jacks',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['calves', 'glutes', 'shoulders', 'abductors'],
    aliases: ['jumping jack', 'jumpingjack', 'star jump', 'side straddle hop'],
  },
  {
    name: 'high knees',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['calves', 'abdominals', 'hamstrings'],
    aliases: [
      'high knee',
      'high knees run',
      'high knee run',
      'high knee march',
    ],
  },
  {
    name: 'butt kicks',
    kind: 'strength',
    primary: ['hamstrings'],
    secondary: ['calves', 'glutes', 'quadriceps'],
    aliases: ['butt kick', 'butt kicker', 'bum kick', 'heel kick'],
  },
  {
    name: 'wall ball',
    kind: 'strength',
    primary: ['quadriceps'],
    secondary: ['shoulders', 'glutes', 'hamstrings', 'triceps'],
    aliases: ['wall ball shot', 'wall ball throw', 'wallball'],
  },
  { name: 'tire flip', source: 'Tire_Flip', aliases: ['tyre flip'] },

  // Cardio
  {
    name: 'jogging',
    source: 'Jogging_Treadmill',
    aliases: [
      'jog',
      'light run',
      'easy run',
      'slow run',
      'treadmill jog',
      'recovery run',
    ],
  },
  {
    name: 'running',
    source: 'Running_Treadmill',
    aliases: [
      'run',
      'treadmill run',
      'treadmill running',
      'treadmill',
      'tempo run',
      'long run',
      'interval run',
      'trail run',
      'trail running',
    ],
  },
  {
    name: 'sprints',
    kind: 'cardio',
    primary: ['quadriceps'],
    secondary: ['hamstrings', 'glutes', 'calves'],
    aliases: [
      'sprint',
      'sprinting',
      'sprint intervals',
      'hill sprints',
      'wind sprints',
      'shuttle run',
      'suicides',
    ],
  },
  {
    name: 'hiking',
    kind: 'cardio',
    primary: ['quadriceps'],
    secondary: ['glutes', 'hamstrings', 'calves'],
    aliases: [
      'hike',
      'hill walking',
      'hill walk',
      'trail walk',
      'trekking',
      'trek',
      'rucking',
      'ruck',
    ],
  },
  {
    name: 'walking',
    source: 'Walking_Treadmill',
    aliases: [
      'walk',
      'treadmill walk',
      'treadmill walking',
      'brisk walk',
      'power walk',
      'power walking',
      'incline walk',
      'incline treadmill',
    ],
  },
  {
    name: 'cycling',
    source: 'Bicycling',
    aliases: [
      'cycle',
      'bike',
      'biking',
      'bike ride',
      'bicycle ride',
      'bicycling',
      'road cycling',
      'mountain biking',
      'mtb',
      'ride',
    ],
  },
  {
    name: 'stationary bike',
    source: 'Bicycling_Stationary',
    aliases: [
      'exercise bike',
      'indoor bike',
      'indoor cycling',
      'spin bike',
      'spinning',
      'spin',
      'spin class',
      'peloton',
      'recumbent bike',
    ],
  },
  {
    name: 'assault bike',
    kind: 'cardio',
    primary: ['quadriceps'],
    secondary: ['hamstrings', 'glutes', 'shoulders', 'chest'],
    aliases: ['air bike', 'airbike', 'airdyne', 'echo bike', 'fan bike'],
  },
  {
    name: 'rowing machine',
    source: 'Rowing_Stationary',
    aliases: [
      'rowing',
      'row machine',
      'rower',
      'erg',
      'ergometer',
      'indoor rowing',
      'rowing erg',
      'concept 2',
      'concept2',
      'rowerg',
    ],
  },
  {
    name: 'ski erg',
    kind: 'cardio',
    primary: ['lats'],
    secondary: ['triceps', 'abdominals', 'shoulders', 'quadriceps'],
    aliases: ['skierg', 'ski-erg', 'ski machine', 'ski ergometer'],
  },
  {
    name: 'elliptical',
    source: 'Elliptical_Trainer',
    aliases: [
      'elliptical trainer',
      'elliptical machine',
      'cross trainer',
      'cross-trainer',
      'crosstrainer',
      'eliptical',
      'arc trainer',
    ],
  },
  {
    name: 'stair climber',
    source: 'Stairmaster',
    aliases: [
      'stairmaster',
      'stair master',
      'stair stepper',
      'stairclimber',
      'stair climbing',
      'stair machine',
      'stairs',
      'stepper',
      'step mill',
      'stepmill',
      'stair running',
    ],
  },
  {
    name: 'swimming',
    kind: 'cardio',
    primary: ['lats'],
    secondary: ['shoulders', 'triceps', 'chest', 'glutes'],
    aliases: [
      'swim',
      'lap swimming',
      'lap swim',
      'swimming laps',
      'swim laps',
      'pool swim',
      'pool laps',
      'freestyle swim',
      'open water swim',
    ],
  },
  {
    name: 'jump rope',
    source: 'Rope_Jumping',
    aliases: [
      'jumping rope',
      'jumprope',
      'rope jumping',
      'rope jump',
      'skipping',
      'skipping rope',
      'skip rope',
      'rope skipping',
      'speed rope',
      'single unders',
      'double unders',
    ],
  },
  {
    name: 'boxing',
    kind: 'cardio',
    primary: ['shoulders'],
    secondary: ['abdominals', 'triceps', 'chest', 'calves'],
    aliases: [
      'boxing workout',
      'boxing class',
      'shadow boxing',
      'shadowboxing',
      'heavy bag',
      'punching bag',
      'bag work',
      'kickboxing',
      'kick boxing',
      'pad work',
      'sparring',
    ],
  },

  // Stretches and mobility (hold)
  {
    name: 'hamstring stretch',
    source: 'Hamstring_Stretch',
    aliases: [
      'standing hamstring stretch',
      'stretch hamstrings',
      'hurdler stretch',
      "hurdler's stretch",
    ],
  },
  {
    name: 'seated hamstring stretch',
    source: 'Seated_Floor_Hamstring_Stretch',
    aliases: [
      'sitting hamstring stretch',
      'seated forward fold',
      'seated forward bend',
      'sit and reach',
      'seated toe touch',
      'paschimottanasana',
    ],
  },
  {
    name: 'lying hamstring stretch',
    source: 'Lying_Hamstring',
    aliases: [
      'supine hamstring stretch',
      'leg up hamstring stretch',
      'strap hamstring stretch',
      'towel hamstring stretch',
      'band hamstring stretch',
      'hamstring stretch with strap',
    ],
  },
  {
    name: 'standing toe touch',
    source: 'Standing_Toe_Touches',
    aliases: [
      'toe touch stretch',
      'forward fold',
      'standing forward fold',
      'forward bend',
      'uttanasana',
      'rag doll',
      'ragdoll',
    ],
  },
  {
    name: "runner's stretch",
    source: 'Runners_Stretch',
    aliases: [
      'runner stretch',
      "runner's lunge",
      'runner lunge',
      'half split',
      'half split stretch',
      'kneeling hamstring stretch',
    ],
  },
  {
    name: 'quad stretch',
    source: 'Quad_Stretch',
    aliases: [
      'quadriceps stretch',
      'standing quad stretch',
      'stretch quads',
      'thigh stretch',
      'front thigh stretch',
      'heel to butt stretch',
      'flamingo stretch',
      'lying quad stretch',
      'prone quad stretch',
      'side lying quad stretch',
    ],
  },
  {
    name: 'hip flexor stretch',
    source: 'Kneeling_Hip_Flexor',
    aliases: [
      'kneeling hip flexor stretch',
      'half kneeling hip flexor stretch',
      'kneeling lunge stretch',
      'low lunge',
      'lunge stretch',
      'psoas stretch',
      'anjaneyasana',
      'crescent lunge',
      'standing hip flexor stretch',
    ],
  },
  {
    name: 'couch stretch',
    kind: 'hold',
    primary: ['quadriceps'],
    secondary: ['glutes'],
    aliases: [
      'couch quad stretch',
      'couch hip flexor stretch',
      'wall couch stretch',
      'rear foot elevated quad stretch',
    ],
  },
  {
    name: 'calf stretch',
    source: 'Calf_Stretch_Hands_Against_Wall',
    aliases: [
      'calves stretch',
      'wall calf stretch',
      'standing calf stretch',
      'gastrocnemius stretch',
      'gastroc stretch',
      'straight leg calf stretch',
      'heel drop stretch',
      'step calf stretch',
    ],
  },
  {
    name: 'soleus stretch',
    source: 'Standing_Soleus_And_Achilles_Stretch',
    aliases: [
      'achilles stretch',
      'achilles tendon stretch',
      'bent knee calf stretch',
      'lower calf stretch',
      'ankle stretch',
      'dorsiflexion stretch',
      'knee to wall stretch',
      'knee to wall',
    ],
  },
  {
    name: 'glute stretch',
    source: 'Lying_Glute',
    aliases: [
      'lying glute stretch',
      'figure four stretch',
      'figure 4 stretch',
      'figure four',
      'figure 4',
      'piriformis stretch',
      'butt stretch',
      'hip stretch',
      'reclined pigeon',
      'dead pigeon',
      'eye of the needle',
    ],
  },
  {
    name: 'seated glute stretch',
    source: 'Seated_Glute',
    aliases: [
      'seated figure four stretch',
      'seated figure 4 stretch',
      'seated figure four',
      'seated figure 4',
      'seated piriformis stretch',
      'chair glute stretch',
      'seated hip stretch',
      'seated pigeon',
    ],
  },
  {
    name: 'pigeon pose',
    kind: 'hold',
    primary: ['glutes'],
    secondary: ['abductors'],
    aliases: [
      'pigeon',
      'pigeon stretch',
      'pigeon hip stretch',
      'sleeping pigeon',
      'resting pigeon',
      'half pigeon',
      'king pigeon',
      'eka pada rajakapotasana',
      'pigeon hip opener',
    ],
  },
  {
    name: 'knee to chest stretch',
    source: 'Hug_Knees_To_Chest',
    aliases: [
      'knees to chest',
      'knee to chest',
      'hug knees to chest',
      'knee hug',
      'single knee to chest',
      'one knee to chest',
      'lower back stretch',
      'low back stretch',
      'back stretch',
      'lumbar stretch',
      'apanasana',
      'wind relieving pose',
    ],
  },
  {
    name: 'butterfly stretch',
    kind: 'hold',
    primary: ['adductors'],
    secondary: ['hamstrings'],
    aliases: [
      'butterfly pose',
      'seated butterfly',
      'butterfly groin stretch',
      'groin stretch',
      'seated groin stretch',
      'bound angle pose',
      'baddha konasana',
      'cobbler pose',
      "cobbler's pose",
      'reclined butterfly',
      'supta baddha konasana',
    ],
  },
  {
    name: 'adductor stretch',
    source: 'Adductor_Groin',
    aliases: [
      'inner thigh stretch',
      'standing groin stretch',
      'standing adductor stretch',
      'side lunge stretch',
      'lateral lunge stretch',
      'wide leg stretch',
      'cossack stretch',
      'adductor rock',
      'adductor rockback',
      'kneeling adductor stretch',
      'hip adductor stretch',
    ],
  },
  {
    name: 'straddle stretch',
    source: 'The_Straddle',
    aliases: [
      'straddle',
      'seated straddle',
      'straddle fold',
      'pancake',
      'pancake stretch',
      'wide leg forward fold',
      'upavistha konasana',
      'v stretch',
      'middle split',
      'center split',
      'centre split',
      'side split',
      'box split',
    ],
  },
  {
    name: 'frog stretch',
    kind: 'hold',
    primary: ['adductors'],
    secondary: ['glutes'],
    aliases: [
      'frog pose',
      'frog',
      'frog hold',
      'frog position',
      'frog groin stretch',
      'frog adductor stretch',
      'frog hip stretch',
      'frog hip opener',
      'mandukasana',
      'bhekasana',
      'frog rock',
      'frog rocking',
      'frog rockback',
      'rocking frog',
      'half frog',
    ],
  },
  {
    name: "child's pose",
    source: 'Childs_Pose',
    aliases: [
      'child pose',
      'balasana',
      "child's pose stretch",
      'extended child pose',
      "extended child's pose",
      'wide knee child pose',
      'resting pose',
    ],
  },
  {
    name: 'cat cow',
    source: 'Cat_Stretch',
    kind: 'strength',
    aliases: [
      'cat-cow',
      'cat/cow',
      'cat cow stretch',
      'cat cow pose',
      'cat and cow',
      'cat stretch',
      'cat camel',
      'cat camel stretch',
      'marjaryasana',
      'bitilasana',
    ],
  },
  {
    name: 'cobra stretch',
    kind: 'hold',
    primary: ['abdominals'],
    secondary: ['lower back', 'chest'],
    aliases: [
      'cobra',
      'cobra pose',
      'bhujangasana',
      'baby cobra',
      'low cobra',
      'high cobra',
      'prone press-up',
      'press-up stretch',
      'sphinx',
      'sphinx pose',
      'sphinx stretch',
    ],
  },
  {
    name: 'spinal twist',
    source: 'Knee_Across_The_Body',
    aliases: [
      'lying spinal twist',
      'supine twist',
      'supine spinal twist',
      'lying twist',
      'reclined twist',
      'knee across body',
      'lumbar twist',
      'lower back twist',
      'supta matsyendrasana',
      'twisted root',
      'lying crossover',
    ],
  },
  {
    name: 'chest stretch',
    source: 'Chest_And_Front_Of_Shoulder_Stretch',
    aliases: [
      'pec stretch',
      'pectoral stretch',
      'doorway chest stretch',
      'doorway stretch',
      'wall chest stretch',
      'chest opener',
      'front shoulder stretch',
      'anterior shoulder stretch',
      'front delt stretch',
      'hands behind back stretch',
      'elbows back',
    ],
  },
  {
    name: 'shoulder stretch',
    source: 'Shoulder_Stretch',
    aliases: [
      'cross body shoulder stretch',
      'cross body stretch',
      'arm across chest stretch',
      'arm across chest',
      'posterior shoulder stretch',
      'rear delt stretch',
      'deltoid stretch',
      'delt stretch',
      'arm hug stretch',
    ],
  },
  {
    name: 'triceps stretch',
    source: 'Triceps_Stretch',
    aliases: [
      'stretch triceps',
      'overhead triceps stretch',
      'behind head triceps stretch',
      'behind the head triceps stretch',
      'elbow behind head stretch',
      'arm behind head stretch',
      'overhead arm stretch',
      'back of arm stretch',
      'upper arm stretch',
      'arm stretch',
    ],
  },
  {
    name: 'biceps stretch',
    source: 'Standing_Biceps_Stretch',
    aliases: [
      'stretch biceps',
      'standing biceps stretch',
      'wall biceps stretch',
      'doorway biceps stretch',
      'arm against wall stretch',
      'front of arm stretch',
    ],
  },
  {
    name: 'lat stretch',
    source: 'Overhead_Lat',
    aliases: [
      'stretch lats',
      'overhead lat stretch',
      'latissimus stretch',
      'side lat stretch',
      'standing lat stretch',
      'kneeling lat stretch',
      'bench lat stretch',
      'wall lat stretch',
      'hanging lat stretch',
    ],
  },
  {
    name: 'forearm stretch',
    source: 'Kneeling_Forearm_Stretch',
    aliases: [
      'wrist stretch',
      'wrist flexor stretch',
      'wrist extensor stretch',
      'kneeling forearm stretch',
      'kneeling wrist stretch',
      'prayer stretch',
      'reverse prayer stretch',
      'wrist extension stretch',
      'wrist flexion stretch',
      'wrist mobility',
    ],
  },
  {
    name: 'neck stretch',
    source: 'Side_Neck_Stretch',
    aliases: [
      'side neck stretch',
      'lateral neck stretch',
      'ear to shoulder stretch',
      'neck tilt',
      'upper trap stretch',
      'trap stretch',
      'levator scapulae stretch',
      'chin to chest stretch',
      'chin to chest',
      'chin tuck',
      'neck flexion stretch',
    ],
  },
  {
    name: 'upper back stretch',
    source: 'Upper_Back_Stretch',
    aliases: [
      'rhomboid stretch',
      'thoracic stretch',
      'thoracic spine stretch',
      't-spine stretch',
      'mid back stretch',
      'middle back stretch',
      'shoulder blade stretch',
      'scapular stretch',
    ],
  },
  {
    name: 'standing side stretch',
    source: 'Standing_Lateral_Stretch',
    aliases: [
      'side stretch',
      'lateral stretch',
      'side bend stretch',
      'oblique stretch',
      'side body stretch',
      'overhead side stretch',
      'half moon stretch',
      'banana stretch',
      'waist stretch',
      'ql stretch',
      'quadratus lumborum stretch',
    ],
  },
  {
    name: 'overhead stretch',
    source: 'Overhead_Stretch',
    aliases: [
      'overhead reach',
      'reach overhead',
      'arms overhead stretch',
      'full body stretch',
      'whole body stretch',
      'upward stretch',
      'upward salute',
      'urdhva hastasana',
      'abdominal stretch',
      'ab stretch',
      'core stretch',
      'torso stretch',
    ],
  },
  {
    name: 'it band stretch',
    source: 'IT_Band_and_Glute_Stretch',
    aliases: [
      'itb stretch',
      'iliotibial band stretch',
      'itband stretch',
      'outer thigh stretch',
      'outer hip stretch',
      'tfl stretch',
      'standing it band stretch',
      'abductor stretch',
      'glute med stretch',
      'side hip stretch',
    ],
  },
  {
    name: 'quad foam roll',
    source: 'Quadriceps-SMR',
    aliases: [
      'foam roll quads',
      'foam roller quads',
      'quad roll',
      'roll quads',
      'quad smr',
      'quad release',
      'thigh foam roll',
    ],
  },
  {
    name: 'hamstring foam roll',
    source: 'Hamstring-SMR',
    aliases: [
      'foam roll hamstrings',
      'foam roller hamstrings',
      'hamstring roll',
      'roll hamstrings',
      'hamstring smr',
      'hamstring release',
    ],
  },
  {
    name: 'calf foam roll',
    source: 'Calves-SMR',
    aliases: [
      'calves foam roll',
      'foam roll calves',
      'foam roller calves',
      'calf roll',
      'roll calves',
      'calf smr',
      'calf release',
      'shin foam roll',
    ],
  },
  {
    name: 'it band foam roll',
    source: 'Iliotibial_Tract-SMR',
    aliases: [
      'itb foam roll',
      'foam roll it band',
      'foam roll itb',
      'foam roller it band',
      'it band roll',
      'roll it band',
      'it band smr',
      'itb smr',
      'outer thigh foam roll',
      'tfl foam roll',
    ],
  },
  {
    name: 'glute foam roll',
    source: 'Piriformis-SMR',
    aliases: [
      'foam roll glutes',
      'foam roller glutes',
      'glute smr',
      'glute release',
      'piriformis foam roll',
      'foam roll piriformis',
      'piriformis release',
      'hip foam roll',
      'lacrosse ball glute',
      'lacrosse ball piriformis',
    ],
  },
  {
    name: 'upper back foam roll',
    source: 'Rhomboids-SMR',
    aliases: [
      'foam roll upper back',
      'foam roller upper back',
      'upper back smr',
      'thoracic foam roll',
      'foam roll thoracic',
      't-spine foam roll',
      'back foam roll',
      'foam roll back',
      'thoracic extension',
      'lat foam roll',
      'foam roll lats',
    ],
  },
  {
    name: 'downward dog',
    kind: 'hold',
    primary: ['hamstrings'],
    secondary: ['calves', 'shoulders', 'lats'],
    aliases: [
      'down dog',
      'downward facing dog',
      'downward dog pose',
      'adho mukha svanasana',
      'downdog',
      'inverted v',
      'pike stretch',
      'pike hold',
      'down dog pedal',
      'three legged dog',
    ],
  },
  {
    name: "world's greatest stretch",
    source: 'Worlds_Greatest_Stretch',
    kind: 'strength',
    aliases: [
      'world greatest stretch',
      'wgs',
      'greatest stretch',
      'spiderman stretch',
      'spider-man stretch',
      'lunge with reach',
      'lunge with rotation',
      'lunge and twist',
      'lunge twist',
      'elbow to instep',
      'elbow to instep stretch',
    ],
  },
]
