import type {
  FoodClass,
  FoodPortions,
  FoodServing,
  PortionKey,
} from '../src/food'

export type CuratedFood = {
  name: string
  fdc: number
  aliases?: readonly string[]
  serving?: PortionKey
  servingLabel?: string
  portions?: FoodPortions
  usdaPortions?: false
  liquid?: true
  class?: FoodClass
}

// An average of existing entries (by id); members without a class inherit it.
export type CuratedGeneric = {
  name: string
  members: readonly string[]
  aliases?: readonly string[]
  serving: FoodServing
  portions?: FoodPortions
  class?: FoodClass
}

export const CURATED_FOODS: readonly CuratedFood[] = [
  // Fruit
  { name: 'apple', fdc: 171688 },
  {
    name: 'green apple',
    fdc: 168203,
    aliases: ['granny smith apple', 'granny smith'],
  },
  {
    name: 'red apple',
    fdc: 168201,
    aliases: ['red delicious apple', 'red delicious'],
  },
  { name: 'fuji apple', fdc: 167793 },
  { name: 'gala apple', fdc: 168204 },
  { name: 'golden delicious apple', fdc: 168202 },
  {
    name: 'applesauce',
    fdc: 171695,
    aliases: ['apple sauce', 'apple puree'],
    serving: 'cup',
  },
  { name: 'apricot', fdc: 171697 },
  {
    name: 'dried apricot',
    fdc: 173941,
    portions: { piece: 7 },
  },
  { name: 'avocado', fdc: 171706, aliases: ['hass avocado'] },
  { name: 'banana', fdc: 173944 },
  { name: 'blackberry', fdc: 173946 },
  { name: 'blueberry', fdc: 171711, serving: 'cup' },
  {
    name: 'cantaloupe',
    fdc: 169092,
    aliases: ['rockmelon', 'cantaloupe melon'],
    serving: 'cup',
  },
  { name: 'cherry', fdc: 171719, aliases: ['sweet cherry'], serving: 'cup' },
  {
    name: 'sour cherry',
    fdc: 173954,
    aliases: ['tart cherry'],
    serving: 'cup',
  },
  { name: 'clementine', fdc: 168195 },
  {
    name: 'coconut',
    fdc: 170169,
    aliases: ['fresh coconut', 'coconut meat'],
    serving: 'cup',
  },
  {
    name: 'shredded coconut',
    fdc: 170577,
    aliases: ['coconut flake', 'desiccated coconut', 'coconut flakes'],
    serving: 'cup',
  },
  { name: 'cranberry', fdc: 171722, serving: 'cup' },
  {
    name: 'dried cranberry',
    fdc: 171723,
    aliases: ['craisin'],
  },
  { name: 'date', fdc: 168191, aliases: ['medjool date'] },
  { name: 'fig', fdc: 173021 },
  { name: 'dried fig', fdc: 174665 },
  { name: 'grapefruit', fdc: 173033 },
  {
    name: 'grape',
    fdc: 174683,
    aliases: ['green grape', 'red grape', 'seedless grape'],
    serving: 'cup',
  },
  { name: 'guava', fdc: 173044 },
  {
    name: 'honeydew',
    fdc: 169911,
    aliases: ['honeydew melon'],
    serving: 'cup',
  },
  { name: 'kiwi', fdc: 168153, aliases: ['kiwifruit', 'kiwi fruit'] },
  { name: 'kumquat', fdc: 168154 },
  { name: 'lemon', fdc: 167746 },
  {
    name: 'lemon juice',
    fdc: 167747,
    portions: { tbsp: 15 },
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'lime', fdc: 168155 },
  {
    name: 'lime juice',
    fdc: 168156,
    portions: { tbsp: 15 },
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'lychee', fdc: 169086, aliases: ['litchi'], serving: 'cup' },
  { name: 'mango', fdc: 169910 },
  { name: 'dried mango', fdc: 169091 },
  { name: 'nectarine', fdc: 169914 },
  {
    name: 'olive',
    fdc: 169094,
    aliases: ['black olive', 'ripe olive', 'kalamata olive'],
    serving: 'large',
  },
  {
    name: 'green olive',
    fdc: 169096,
    aliases: ['pickled olive', 'manzanilla olive'],
  },
  { name: 'orange', fdc: 169097, portions: { medium: 131 } },
  { name: 'navel orange', fdc: 169917 },
  {
    name: 'orange juice',
    fdc: 169098,
    aliases: ['oj', 'fresh orange juice'],
    serving: 'cup',
    liquid: true,
  },
  { name: 'papaya', fdc: 169926, serving: 'cup' },
  { name: 'passion fruit', fdc: 169108, aliases: ['passionfruit'] },
  { name: 'peach', fdc: 169928 },
  { name: 'pear', fdc: 169118 },
  { name: 'asian pear', fdc: 168177, aliases: ['nashi pear'] },
  { name: 'persimmon', fdc: 169941 },
  { name: 'pineapple', fdc: 169124, serving: 'cup' },
  {
    name: 'canned pineapple',
    fdc: 169126,
    aliases: ['tinned pineapple'],
    serving: 'cup',
  },
  { name: 'plantain', fdc: 169130 },
  { name: 'plum', fdc: 169949 },
  { name: 'prune', fdc: 168162, aliases: ['dried plum'] },
  { name: 'pomegranate', fdc: 169134 },
  { name: 'raisin', fdc: 168165, aliases: ['sultana'] },
  { name: 'golden raisin', fdc: 168164, class: 'dried fruit' },
  { name: 'raspberry', fdc: 167755, serving: 'cup' },
  { name: 'rhubarb', fdc: 167758, serving: 'cup' },
  { name: 'strawberry', fdc: 167762, serving: 'cup' },
  {
    name: 'tangerine',
    fdc: 169105,
    aliases: ['mandarin', 'mandarin orange', 'satsuma'],
  },
  {
    name: 'canned mandarin',
    fdc: 169106,
    aliases: ['canned mandarin orange', 'mandarin segment'],
    serving: 'cup',
  },
  { name: 'watermelon', fdc: 167765, serving: 'cup' },
  { name: 'star fruit', fdc: 171715, aliases: ['starfruit', 'carambola'] },
  { name: 'jackfruit', fdc: 174687, serving: 'cup' },
  { name: 'mulberry', fdc: 169913, serving: 'cup' },
  { name: 'gooseberry', fdc: 173030, serving: 'cup' },
  { name: 'red currant', fdc: 173964, aliases: ['redcurrant'], serving: 'cup' },
  {
    name: 'black currant',
    fdc: 173963,
    aliases: ['blackcurrant'],
    serving: 'cup',
  },
  { name: 'elderberry', fdc: 171727, serving: 'cup' },
  { name: 'quince', fdc: 168163 },
  {
    name: 'fruit cocktail',
    fdc: 173028,
    aliases: ['canned fruit cocktail', 'fruit cup'],
    serving: 'cup',
  },
  {
    name: 'canned peach',
    fdc: 169930,
    aliases: ['tinned peach'],
    serving: 'cup',
  },
  {
    name: 'canned pear',
    fdc: 169936,
    aliases: ['tinned pear'],
    serving: 'cup',
  },
  { name: 'maraschino cherry', fdc: 167766, aliases: ['cocktail cherry'] },
  { name: 'apple juice', fdc: 173933, serving: 'cup', liquid: true },
  { name: 'grape juice', fdc: 173042, serving: 'cup', liquid: true },
  {
    name: 'cranberry juice',
    fdc: 168117,
    aliases: ['unsweetened cranberry juice'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'cranberry juice cocktail',
    fdc: 171903,
    aliases: ['cranberry cocktail'],
    serving: 'cup',
    liquid: true,
  },
  { name: 'pineapple juice', fdc: 169947, serving: 'cup', liquid: true },
  { name: 'grapefruit juice', fdc: 173039, serving: 'cup', liquid: true },
  { name: 'tomato juice', fdc: 170458, serving: 'cup', liquid: true },
  { name: 'carrot juice', fdc: 170491, serving: 'cup', liquid: true },
  { name: 'prune juice', fdc: 167753, serving: 'cup', liquid: true },
  { name: 'pomegranate juice', fdc: 167787, serving: 'cup', liquid: true },
  { name: 'lemonade', fdc: 173217, serving: 'cup', liquid: true },
  { name: 'fruit punch', fdc: 171914, serving: 'cup', liquid: true },
  { name: 'coconut water', fdc: 174831, serving: 'cup', liquid: true },

  // Vegetables
  { name: 'artichoke', fdc: 169205, aliases: ['globe artichoke'] },
  {
    name: 'arugula',
    fdc: 169387,
    aliases: ['rocket', 'rocket lettuce', 'roquette'],
    serving: 'cup',
  },
  { name: 'asparagus', fdc: 168389, serving: 'cup' },
  { name: 'bamboo shoot', fdc: 169210, serving: 'cup' },
  {
    name: 'bean sprout',
    fdc: 169957,
    aliases: ['mung bean sprout'],
    serving: 'cup',
  },
  { name: 'beet', fdc: 169145, aliases: ['beetroot'] },
  {
    name: 'canned beet',
    fdc: 169966,
    aliases: ['pickled beet', 'canned beetroot'],
    serving: 'cup',
  },
  { name: 'beet greens', fdc: 170375, aliases: ['beet green'], serving: 'cup' },
  {
    name: 'bell pepper',
    fdc: 170108,
    aliases: [
      'red bell pepper',
      'red pepper',
      'capsicum',
      'sweet pepper',
      'red capsicum',
    ],
  },
  {
    name: 'green bell pepper',
    fdc: 170427,
    aliases: ['green pepper', 'green capsicum'],
  },
  {
    name: 'yellow bell pepper',
    fdc: 169383,
    aliases: ['yellow pepper', 'yellow capsicum'],
  },
  {
    name: 'bok choy',
    fdc: 170390,
    aliases: ['pak choi', 'pak choy', 'bok choi'],
    serving: 'cup',
  },
  {
    name: 'napa cabbage',
    fdc: 169979,
    aliases: ['chinese cabbage', 'wombok'],
    serving: 'cup',
  },
  {
    name: 'broccoli',
    fdc: 170379,
    serving: 'cup',
    usdaPortions: false,
    portions: { cup: 91, medium: 151 },
  },
  { name: 'frozen broccoli', fdc: 169968, serving: 'cup' },
  { name: 'chinese broccoli', fdc: 169404, aliases: ['gai lan', 'kai lan'] },
  { name: 'broccoli rabe', fdc: 170381, aliases: ['rapini'], serving: 'cup' },
  {
    name: 'brussels sprout',
    fdc: 170383,
    aliases: ['brussel sprout'],
    serving: 'cup',
  },
  {
    name: 'butternut squash',
    fdc: 169295,
    aliases: ['butternut pumpkin'],
    serving: 'cup',
  },
  { name: 'acorn squash', fdc: 168472, serving: 'cup' },
  { name: 'spaghetti squash', fdc: 169298, serving: 'cup' },
  { name: 'winter squash', fdc: 170489, aliases: ['squash'], serving: 'cup' },
  { name: 'pumpkin', fdc: 168448, serving: 'cup' },
  {
    name: 'canned pumpkin',
    fdc: 168450,
    aliases: ['pumpkin puree'],
    serving: 'cup',
  },
  {
    name: 'cabbage',
    fdc: 169975,
    aliases: ['green cabbage', 'white cabbage'],
    serving: 'cup',
  },
  {
    name: 'red cabbage',
    fdc: 169977,
    aliases: ['purple cabbage'],
    serving: 'cup',
  },
  { name: 'savoy cabbage', fdc: 170388, serving: 'cup' },
  { name: 'kale', fdc: 168421, aliases: ['curly kale'], serving: 'cup' },
  { name: 'sauerkraut', fdc: 169279, serving: 'cup' },
  { name: 'kimchi', fdc: 170392, serving: 'cup' },
  { name: 'carrot', fdc: 170393 },
  { name: 'baby carrot', fdc: 168568 },
  {
    name: 'cauliflower',
    fdc: 169986,
    serving: 'cup',
    usdaPortions: false,
    portions: { cup: 107, small: 265, medium: 588, large: 840 },
  },
  { name: 'celery', fdc: 169988 },
  { name: 'celeriac', fdc: 170400, aliases: ['celery root'], serving: 'cup' },
  {
    name: 'swiss chard',
    fdc: 169991,
    aliases: ['chard', 'silverbeet'],
    serving: 'cup',
  },
  { name: 'chives', fdc: 169994, aliases: ['chive'], serving: 'tbsp' },
  {
    name: 'collard greens',
    fdc: 170406,
    aliases: ['collards', 'collard green', 'collard'],
    serving: 'cup',
  },
  {
    name: 'corn',
    fdc: 169998,
    aliases: [
      'sweet corn',
      'corn on the cob',
      'fresh corn',
      'corn cob',
      'sweetcorn',
    ],
  },
  {
    name: 'canned corn',
    fdc: 169214,
    aliases: ['tinned corn', 'canned sweetcorn'],
    serving: 'cup',
  },
  {
    name: 'creamed corn',
    fdc: 169215,
    aliases: ['cream style corn'],
    serving: 'cup',
  },
  { name: 'frozen corn', fdc: 168398, serving: 'cup' },
  { name: 'cucumber', fdc: 168409 },
  { name: 'eggplant', fdc: 169228, aliases: ['aubergine', 'brinjal'] },
  { name: 'endive', fdc: 168412, serving: 'cup' },
  { name: 'radicchio', fdc: 168564, serving: 'cup' },
  { name: 'fennel', fdc: 169385, aliases: ['fennel bulb'] },
  { name: 'garlic', fdc: 169230, serving: 'clove' },
  {
    name: 'ginger',
    fdc: 169231,
    aliases: ['ginger root', 'fresh ginger'],
    portions: { tbsp: 6 },
    serving: 'tbsp',
  },
  {
    name: 'green bean',
    fdc: 169961,
    aliases: ['string bean', 'snap bean', 'french bean', 'haricot vert'],
    serving: 'cup',
  },
  { name: 'yellow bean', fdc: 169320, aliases: ['wax bean'], serving: 'cup' },
  {
    name: 'green onion',
    fdc: 170005,
    aliases: ['scallion', 'spring onion', 'salad onion'],
  },
  { name: 'jalapeno', fdc: 168576, aliases: ['jalapeño', 'jalapeno pepper'] },
  {
    name: 'serrano pepper',
    fdc: 169395,
    aliases: ['serrano chili', 'serrano'],
  },
  {
    name: 'chili pepper',
    fdc: 170106,
    aliases: ['red chili', 'red chilli', 'hot pepper', 'red chile'],
  },
  {
    name: 'green chili',
    fdc: 170497,
    aliases: ['green chilli', 'green chile'],
  },
  { name: 'banana pepper', fdc: 169394 },
  { name: 'jicama', fdc: 170073, aliases: ['yam bean'], serving: 'cup' },
  { name: 'kohlrabi', fdc: 168424, serving: 'cup' },
  { name: 'leek', fdc: 169246, serving: 'piece' },
  {
    name: 'iceberg lettuce',
    fdc: 169248,
    aliases: ['lettuce'],
    serving: 'cup',
  },
  {
    name: 'romaine lettuce',
    fdc: 169247,
    aliases: ['romaine', 'cos lettuce'],
    serving: 'cup',
  },
  {
    name: 'green leaf lettuce',
    fdc: 169249,
    aliases: ['leaf lettuce'],
    serving: 'cup',
  },
  { name: 'red leaf lettuce', fdc: 168431, serving: 'cup' },
  {
    name: 'butter lettuce',
    fdc: 168429,
    aliases: ['boston lettuce', 'bibb lettuce', 'butterhead lettuce'],
    serving: 'cup',
  },
  { name: 'spinach', fdc: 168462, aliases: ['baby spinach'], serving: 'cup' },
  { name: 'frozen spinach', fdc: 169287, serving: 'cup' },
  { name: 'watercress', fdc: 170068, serving: 'cup' },
  {
    name: 'dandelion greens',
    fdc: 169226,
    aliases: ['dandelion green'],
    serving: 'cup',
  },
  {
    name: 'mustard greens',
    fdc: 169256,
    aliases: ['mustard green'],
    serving: 'cup',
  },
  {
    name: 'turnip greens',
    fdc: 170061,
    aliases: ['turnip green'],
    serving: 'cup',
  },
  {
    name: 'mushroom',
    fdc: 169251,
    aliases: ['white mushroom', 'button mushroom'],
  },
  {
    name: 'cremini mushroom',
    fdc: 168434,
    aliases: [
      'cremini',
      'crimini',
      'baby bella',
      'brown mushroom',
      'chestnut mushroom',
    ],
  },
  {
    name: 'portobello mushroom',
    fdc: 169255,
    aliases: ['portobello', 'portabella', 'portabella mushroom'],
  },
  { name: 'shiitake mushroom', fdc: 169242, aliases: ['shiitake'] },
  { name: 'dried shiitake', fdc: 168436, aliases: ['dried shiitake mushroom'] },
  { name: 'oyster mushroom', fdc: 168580, serving: 'cup' },
  { name: 'enoki mushroom', fdc: 169382, aliases: ['enoki'], serving: 'cup' },
  { name: 'canned mushroom', fdc: 169254, serving: 'cup' },
  { name: 'okra', fdc: 169260, serving: 'cup' },
  {
    name: 'onion',
    fdc: 170000,
    aliases: [
      'yellow onion',
      'brown onion',
      'red onion',
      'white onion',
      'cooking onion',
    ],
  },
  { name: 'sweet onion', fdc: 170008, aliases: ['vidalia onion'] },
  { name: 'shallot', fdc: 170499, serving: 'tbsp' },
  { name: 'parsnip', fdc: 170417, serving: 'cup' },
  {
    name: 'pea',
    fdc: 170419,
    aliases: ['green pea', 'garden pea'],
    serving: 'cup',
  },
  { name: 'frozen pea', fdc: 170016, serving: 'cup' },
  {
    name: 'snow pea',
    fdc: 170010,
    aliases: ['snap pea', 'sugar snap pea', 'sugar snap', 'mangetout'],
    serving: 'cup',
  },
  { name: 'edamame', fdc: 168411, serving: 'cup' },
  { name: 'potato', fdc: 170026 },
  {
    name: 'russet potato',
    fdc: 170027,
    aliases: ['baking potato', 'idaho potato'],
  },
  { name: 'red potato', fdc: 170029, aliases: ['new potato'] },
  { name: 'baked potato', fdc: 170093, aliases: ['jacket potato'] },
  { name: 'boiled potato', fdc: 170440 },
  {
    name: 'mashed potatoes',
    fdc: 168555,
    aliases: ['mashed potato', 'mash'],
    serving: 'cup',
  },
  {
    name: 'french fries',
    fdc: 169264,
    aliases: ['french fry', 'fries', 'fry', 'oven fries', 'frozen fries'],
    usdaPortions: false,
  },
  { name: 'hash browns', fdc: 170036, aliases: ['hash brown'], serving: 'cup' },
  { name: 'sweet potato', fdc: 168482, aliases: ['kumara'] },
  { name: 'baked sweet potato', fdc: 168483 },
  { name: 'yam', fdc: 170071, serving: 'cup' },
  { name: 'radish', fdc: 169276, serving: 'cup' },
  {
    name: 'daikon',
    fdc: 168451,
    aliases: ['daikon radish', 'oriental radish', 'mooli'],
    serving: 'cup',
  },
  { name: 'rutabaga', fdc: 168454, aliases: ['swede'] },
  { name: 'turnip', fdc: 170465 },
  {
    name: 'nori',
    fdc: 168458,
    aliases: ['laver', 'nori sheet', 'seaweed sheet'],
  },
  { name: 'wakame', fdc: 170496, aliases: ['seaweed'], serving: 'tbsp' },
  { name: 'kelp', fdc: 168457, serving: 'tbsp' },
  { name: 'spirulina', fdc: 170495, serving: 'tbsp' },
  { name: 'zucchini', fdc: 169291, aliases: ['courgette'] },
  {
    name: 'yellow squash',
    fdc: 168464,
    aliases: ['summer squash', 'crookneck squash'],
    serving: 'cup',
  },
  {
    name: 'tomato',
    fdc: 170457,
    aliases: ['roma tomato', 'plum tomato', 'vine tomato'],
  },
  {
    name: 'cherry tomato',
    fdc: 170457,
    aliases: ['grape tomato', 'baby tomato'],
    usdaPortions: false,
    portions: { piece: 17, medium: 17, cup: 149 },
  },
  {
    name: 'canned tomato',
    fdc: 170051,
    aliases: [
      'canned tomatoes',
      'diced tomato',
      'diced tomatoes',
      'whole peeled tomato',
      'tinned tomato',
      'tinned tomatoes',
      'chopped tomato',
      'chopped tomatoes',
    ],
    serving: 'cup',
  },
  {
    name: 'tomato paste',
    fdc: 170459,
    aliases: ['tomato concentrate'],
    serving: 'tbsp',
  },
  { name: 'tomato puree', fdc: 170460, aliases: ['passata'], serving: 'cup' },
  { name: 'tomato sauce', fdc: 170054, serving: 'cup' },
  {
    name: 'sun-dried tomato',
    fdc: 168567,
    aliases: ['sundried tomato', 'sun dried tomato'],
    serving: 'piece',
  },
  { name: 'tomatillo', fdc: 168566 },
  { name: 'water chestnut', fdc: 170066, serving: 'cup' },
  { name: 'cassava', fdc: 169985, aliases: ['yuca', 'manioc'], serving: 'cup' },
  { name: 'taro', fdc: 169308, serving: 'cup' },
  {
    name: 'hearts of palm',
    fdc: 167714,
    aliases: ['heart of palm', 'palm heart'],
  },
  {
    name: 'alfalfa sprouts',
    fdc: 168384,
    aliases: ['alfalfa sprout'],
    serving: 'cup',
  },
  {
    name: 'pickle',
    fdc: 168558,
    aliases: ['dill pickle', 'gherkin', 'pickled cucumber'],
    portions: { piece: 65 },
    serving: 'piece',
  },
  {
    name: 'sweet pickle',
    fdc: 169378,
    aliases: ['bread and butter pickle'],
    serving: 'cup',
  },
  {
    name: 'relish',
    fdc: 168561,
    aliases: ['pickle relish', 'sweet relish'],
    serving: 'tbsp',
  },
  { name: 'caper', fdc: 172238, serving: 'tbsp' },
  {
    name: 'mixed vegetables',
    fdc: 170471,
    aliases: [
      'mixed vegetable',
      'frozen vegetables',
      'frozen vegetable',
      'frozen mixed vegetables',
      'mixed veg',
    ],
  },
  { name: 'peas and carrots', fdc: 170425, serving: 'cup' },
  {
    name: 'horseradish',
    fdc: 173472,
    aliases: ['prepared horseradish'],
    serving: 'tsp',
  },
  {
    name: 'lemongrass',
    fdc: 168573,
    aliases: ['lemon grass'],
    serving: 'tbsp',
  },

  // Fresh herbs
  {
    name: 'cilantro',
    fdc: 169997,
    aliases: ['coriander', 'fresh coriander', 'coriander leaf'],
    serving: 'cup',
  },
  {
    name: 'parsley',
    fdc: 170416,
    aliases: ['fresh parsley', 'flat-leaf parsley', 'italian parsley'],
    serving: 'tbsp',
  },
  {
    name: 'basil',
    fdc: 172232,
    aliases: ['fresh basil', 'basil leaf'],
    serving: 'tbsp',
  },
  {
    name: 'dill',
    fdc: 172233,
    aliases: ['fresh dill', 'dill weed'],
    serving: 'cup',
  },
  {
    name: 'mint',
    fdc: 173475,
    aliases: ['spearmint', 'fresh mint', 'mint leaf'],
    serving: 'tbsp',
  },
  { name: 'peppermint', fdc: 173474, serving: 'tbsp' },
  {
    name: 'rosemary',
    fdc: 173473,
    aliases: ['fresh rosemary'],
    serving: 'tsp',
  },
  { name: 'thyme', fdc: 173470, aliases: ['fresh thyme'], serving: 'tsp' },

  // Dried spices, baking staples, and seasonings
  {
    name: 'black pepper',
    fdc: 170931,
    aliases: ['ground pepper', 'ground black pepper', 'peppercorn'],
    serving: 'tsp',
  },
  { name: 'white pepper', fdc: 170933, serving: 'tsp' },
  {
    name: 'cayenne pepper',
    fdc: 170932,
    aliases: [
      'cayenne',
      'red pepper flake',
      'chili flake',
      'crushed red pepper',
    ],
    serving: 'tsp',
  },
  {
    name: 'paprika',
    fdc: 171329,
    aliases: ['smoked paprika', 'sweet paprika'],
    serving: 'tsp',
  },
  {
    name: 'chili powder',
    fdc: 171319,
    aliases: ['chilli powder'],
    serving: 'tsp',
  },
  {
    name: 'cumin',
    fdc: 170923,
    aliases: ['ground cumin', 'cumin seed'],
    serving: 'tsp',
  },
  {
    name: 'coriander seed',
    fdc: 170922,
    aliases: ['ground coriander'],
    serving: 'tsp',
  },
  { name: 'curry powder', fdc: 170924, serving: 'tsp' },
  {
    name: 'turmeric',
    fdc: 172231,
    aliases: ['ground turmeric', 'turmeric powder'],
    serving: 'tsp',
  },
  {
    name: 'ground ginger',
    fdc: 170926,
    aliases: ['ginger powder', 'dried ginger'],
    serving: 'tsp',
  },
  {
    name: 'cinnamon',
    fdc: 171320,
    aliases: ['ground cinnamon', 'cinnamon powder'],
    serving: 'tsp',
  },
  { name: 'nutmeg', fdc: 171326, aliases: ['ground nutmeg'], serving: 'tsp' },
  {
    name: 'ground clove',
    fdc: 171321,
    aliases: ['whole clove', 'clove spice'],
    serving: 'tsp',
  },
  { name: 'allspice', fdc: 171315, serving: 'tsp' },
  {
    name: 'cardamom',
    fdc: 170919,
    aliases: ['ground cardamom', 'cardamom pod'],
    serving: 'tsp',
  },
  {
    name: 'garlic powder',
    fdc: 171325,
    aliases: ['granulated garlic'],
    serving: 'tsp',
  },
  { name: 'onion powder', fdc: 171327, serving: 'tsp' },
  { name: 'dried basil', fdc: 171317, serving: 'tsp' },
  { name: 'dried oregano', fdc: 171328, aliases: ['oregano'], serving: 'tsp' },
  { name: 'dried parsley', fdc: 170930, serving: 'tsp' },
  { name: 'dried thyme', fdc: 170938, serving: 'tsp' },
  { name: 'dried rosemary', fdc: 171333, serving: 'tsp' },
  { name: 'dried dill', fdc: 171322, serving: 'tsp' },
  {
    name: 'marjoram',
    fdc: 170928,
    aliases: ['dried marjoram'],
    serving: 'tsp',
  },
  {
    name: 'tarragon',
    fdc: 170937,
    aliases: ['dried tarragon'],
    serving: 'tsp',
  },
  {
    name: 'sage',
    fdc: 170935,
    aliases: ['ground sage', 'dried sage'],
    serving: 'tsp',
  },
  { name: 'bay leaf', fdc: 170917, serving: 'tsp' },
  { name: 'saffron', fdc: 170934, serving: 'tsp' },
  { name: 'poppy seed', fdc: 171330, aliases: ['poppyseed'], serving: 'tsp' },
  { name: 'fennel seed', fdc: 171323, serving: 'tsp' },
  { name: 'caraway seed', fdc: 170918, aliases: ['caraway'], serving: 'tsp' },
  { name: 'celery seed', fdc: 170920, serving: 'tsp' },
  {
    name: 'mustard powder',
    fdc: 170929,
    aliases: ['ground mustard', 'mustard seed'],
    serving: 'tsp',
  },
  {
    name: 'fenugreek',
    fdc: 171324,
    aliases: ['fenugreek seed', 'methi'],
    serving: 'tsp',
  },
  {
    name: 'anise seed',
    fdc: 171316,
    aliases: ['aniseed', 'anise'],
    serving: 'tsp',
  },
  {
    name: 'pumpkin pie spice',
    fdc: 171332,
    aliases: ['mixed spice'],
    serving: 'tsp',
  },
  { name: 'poultry seasoning', fdc: 171331, serving: 'tsp' },
  {
    name: 'taco seasoning',
    fdc: 172243,
    aliases: ['taco seasoning mix'],
    serving: 'tsp',
  },
  {
    name: 'chili seasoning',
    fdc: 173476,
    aliases: ['chili seasoning mix'],
    serving: 'tbsp',
  },
  {
    name: 'salt',
    fdc: 173468,
    aliases: ['table salt', 'sea salt', 'kosher salt', 'fine salt'],
    serving: 'tsp',
  },
  {
    name: 'vanilla extract',
    fdc: 173471,
    aliases: ['vanilla', 'vanilla essence'],
    serving: 'tsp',
  },
  { name: 'baking powder', fdc: 172803, serving: 'tsp' },
  {
    name: 'baking soda',
    fdc: 175040,
    aliases: ['bicarbonate of soda', 'bicarb', 'sodium bicarbonate'],
    serving: 'tsp',
  },
  { name: 'cream of tartar', fdc: 175041, serving: 'tsp' },
  {
    name: 'yeast',
    fdc: 175043,
    aliases: ['active dry yeast', 'dry yeast', 'instant yeast', 'bakers yeast'],
    serving: 'tsp',
  },
  {
    name: 'gelatin',
    fdc: 169599,
    aliases: ['gelatine', 'unflavored gelatin'],
    portions: { tbsp: 7 },
    serving: 'tbsp',
  },
  {
    name: 'cornstarch',
    fdc: 169698,
    aliases: ['corn starch', 'cornflour', 'corn flour'],
    portions: { tbsp: 8 },
    serving: 'tbsp',
  },

  // Condiments, sauces, and soups
  {
    name: 'mustard',
    fdc: 172234,
    aliases: [
      'yellow mustard',
      'prepared mustard',
      'dijon mustard',
      'dijon',
      'wholegrain mustard',
    ],
    serving: 'tsp',
  },
  {
    name: 'ketchup',
    fdc: 168556,
    aliases: ['catsup', 'tomato ketchup'],
    serving: 'tbsp',
  },
  { name: 'mayonnaise', fdc: 171009, aliases: ['mayo'], serving: 'tbsp' },
  {
    name: 'white vinegar',
    fdc: 172237,
    aliases: ['vinegar', 'distilled vinegar'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'apple cider vinegar',
    fdc: 173469,
    aliases: ['cider vinegar'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'red wine vinegar', fdc: 172240, serving: 'tbsp', liquid: true },
  {
    name: 'balsamic vinegar',
    fdc: 172241,
    aliases: ['balsamic'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'soy sauce',
    fdc: 174277,
    aliases: ['shoyu', 'soya sauce'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'tamari',
    fdc: 174278,
    aliases: ['tamari sauce'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'teriyaki sauce', fdc: 171167, serving: 'tbsp', liquid: true },
  { name: 'hoisin sauce', fdc: 172886, aliases: ['hoisin'], serving: 'tbsp' },
  { name: 'oyster sauce', fdc: 174529, serving: 'tbsp' },
  { name: 'fish sauce', fdc: 174531, serving: 'tbsp', liquid: true },
  {
    name: 'worcestershire sauce',
    fdc: 171610,
    aliases: ['worcestershire'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'hot sauce',
    fdc: 174527,
    aliases: ['tabasco', 'pepper sauce', 'chili sauce'],
    serving: 'tsp',
  },
  {
    name: 'sriracha',
    fdc: 171186,
    aliases: ['sriracha sauce'],
    serving: 'tsp',
  },
  { name: 'salsa', fdc: 174524, aliases: ['tomato salsa'], serving: 'tbsp' },
  {
    name: 'salsa verde',
    fdc: 171824,
    aliases: ['green salsa'],
    serving: 'tbsp',
  },
  {
    name: 'bbq sauce',
    fdc: 174523,
    aliases: ['barbecue sauce', 'barbeque sauce', 'barbecue'],
    serving: 'tbsp',
  },
  {
    name: 'marinara sauce',
    fdc: 171192,
    aliases: [
      'marinara',
      'pasta sauce',
      'spaghetti sauce',
      'tomato pasta sauce',
      'red sauce',
    ],
    portions: { cup: 264 },
    serving: 'cup',
  },
  {
    name: 'pesto',
    fdc: 171580,
    aliases: ['basil pesto', 'pesto sauce'],
    portions: { tbsp: 15 },
    serving: 'tbsp',
  },
  { name: 'cheese sauce', fdc: 171191, aliases: ['queso'], serving: 'cup' },
  { name: 'pizza sauce', fdc: 172880, serving: 'cup' },
  { name: 'enchilada sauce', fdc: 174074, serving: 'cup' },
  {
    name: 'sweet and sour sauce',
    fdc: 174066,
    aliases: ['sweet & sour sauce'],
    serving: 'tbsp',
  },
  {
    name: 'tartar sauce',
    fdc: 171826,
    aliases: ['tartare sauce'],
    serving: 'tbsp',
  },
  {
    name: 'cocktail sauce',
    fdc: 174067,
    portions: { tbsp: 15 },
    serving: 'tbsp',
  },
  { name: 'plum sauce', fdc: 172879, serving: 'tbsp' },
  {
    name: 'peanut sauce',
    fdc: 174070,
    aliases: ['satay sauce'],
    serving: 'tbsp',
  },
  {
    name: 'hummus',
    fdc: 174289,
    aliases: ['houmous', 'hommus'],
    serving: 'tbsp',
  },
  {
    name: 'tahini',
    fdc: 170189,
    aliases: ['sesame paste', 'tahina'],
    serving: 'tbsp',
  },
  { name: 'miso', fdc: 172442, aliases: ['miso paste'], serving: 'tbsp' },
  { name: 'chicken gravy', fdc: 171566, aliases: ['gravy'], serving: 'cup' },
  { name: 'beef gravy', fdc: 171564, serving: 'cup' },
  { name: 'turkey gravy', fdc: 171568, serving: 'cup' },
  { name: 'ranch dressing', fdc: 173592, aliases: ['ranch'], serving: 'tbsp' },
  { name: 'caesar dressing', fdc: 169055, serving: 'tbsp' },
  { name: 'italian dressing', fdc: 171019, serving: 'tbsp' },
  { name: 'blue cheese dressing', fdc: 173562, serving: 'tbsp' },
  {
    name: 'thousand island dressing',
    fdc: 171402,
    aliases: ['thousand island'],
    serving: 'tbsp',
  },
  { name: 'french dressing', fdc: 171414, serving: 'tbsp' },
  {
    name: 'honey mustard dressing',
    fdc: 171043,
    aliases: ['honey mustard'],
    serving: 'tbsp',
  },
  { name: 'cranberry sauce', fdc: 173961, serving: 'cup' },
  {
    name: 'chicken broth',
    fdc: 174536,
    aliases: ['chicken stock', 'chicken bouillon'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'beef broth',
    fdc: 171538,
    aliases: ['beef stock', 'beef bouillon'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'vegetable broth',
    fdc: 171583,
    aliases: ['vegetable stock', 'veggie stock', 'veg stock'],
    serving: 'cup',
    liquid: true,
  },
  { name: 'chicken noodle soup', fdc: 171543, serving: 'cup' },
  { name: 'tomato soup', fdc: 172882, serving: 'cup' },
  {
    name: 'cream of mushroom soup',
    fdc: 171155,
    aliases: ['mushroom soup'],
    serving: 'cup',
  },
  { name: 'cream of chicken soup', fdc: 171146, serving: 'cup' },
  {
    name: 'minestrone',
    fdc: 171153,
    aliases: ['minestrone soup'],
    serving: 'cup',
  },
  { name: 'clam chowder', fdc: 174062, serving: 'cup' },
  { name: 'lentil soup', fdc: 171549, serving: 'cup' },
  { name: 'black bean soup', fdc: 171141, serving: 'cup' },
  {
    name: 'onion soup',
    fdc: 171551,
    aliases: ['french onion soup'],
    serving: 'cup',
  },
  {
    name: 'vegetable beef soup',
    fdc: 171163,
    aliases: ['vegetable soup'],
    serving: 'cup',
  },
  {
    name: 'ramen',
    fdc: 171177,
    aliases: [
      'instant noodle',
      'instant noodles',
      'ramen noodle',
      'ramen noodles',
      'instant ramen',
    ],
    portions: { piece: 81 },
    serving: 'piece',
    servingLabel: 'pack',
  },

  // Dairy and eggs
  {
    name: 'egg',
    fdc: 171287,
    aliases: ['chicken egg', 'whole egg'],
    serving: 'large',
  },
  { name: 'egg white', fdc: 172183, serving: 'large' },
  { name: 'egg yolk', fdc: 172184, serving: 'large' },
  {
    name: 'hard-boiled egg',
    fdc: 173424,
    aliases: ['boiled egg', 'hard boiled egg', 'hardboiled egg'],
    serving: 'large',
  },
  { name: 'scrambled egg', fdc: 172187, serving: 'large' },
  { name: 'fried egg', fdc: 173423, serving: 'large' },
  { name: 'poached egg', fdc: 172186, serving: 'large' },
  { name: 'omelette', fdc: 172185, aliases: ['omelet'], serving: 'large' },
  { name: 'duck egg', fdc: 172189 },
  { name: 'quail egg', fdc: 172191 },
  {
    name: 'milk',
    fdc: 171265,
    aliases: [
      'whole milk',
      'full-fat milk',
      'full cream milk',
      'dairy milk',
      'cow milk',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'reduced-fat milk',
    fdc: 171267,
    aliases: [
      '2% milk',
      'semi-skimmed milk',
      'semi skimmed milk',
      '2 percent milk',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'low-fat milk',
    fdc: 170872,
    aliases: ['1% milk', 'lowfat milk', 'low fat milk', '1 percent milk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'skim milk',
    fdc: 171269,
    aliases: [
      'fat-free milk',
      'nonfat milk',
      'skimmed milk',
      'fat free milk',
      'non-fat milk',
    ],
    serving: 'cup',
    liquid: true,
  },
  { name: 'chocolate milk', fdc: 170879, serving: 'cup', liquid: true },
  { name: 'buttermilk', fdc: 170874, serving: 'cup', liquid: true },
  { name: 'evaporated milk', fdc: 171276, serving: 'cup', liquid: true },
  {
    name: 'condensed milk',
    fdc: 171275,
    aliases: ['sweetened condensed milk'],
    portions: { tbsp: 19 },
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'heavy cream',
    fdc: 170859,
    aliases: [
      'heavy whipping cream',
      'double cream',
      'whipping cream',
      'thickened cream',
    ],
    portions: { cup: 238 },
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'light cream',
    fdc: 170857,
    aliases: ['single cream', 'coffee cream', 'table cream', 'pouring cream'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'half and half',
    fdc: 171255,
    aliases: ['half-and-half'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'whipped cream',
    fdc: 170860,
    aliases: ['whipped topping', 'squirty cream'],
    serving: 'tbsp',
  },
  {
    name: 'sour cream',
    fdc: 171257,
    aliases: ['soured cream'],
    serving: 'tbsp',
  },
  {
    name: 'cream cheese',
    fdc: 173418,
    aliases: ['philadelphia'],
    serving: 'tbsp',
  },
  { name: 'butter', fdc: 173410, aliases: ['salted butter'], serving: 'tbsp' },
  { name: 'unsalted butter', fdc: 173430, serving: 'tbsp' },
  {
    name: 'ghee',
    fdc: 171314,
    aliases: ['clarified butter'],
    portions: { tbsp: 13, tsp: 4.3, cup: 205 },
    serving: 'tbsp',
  },
  {
    name: 'margarine',
    fdc: 172346,
    aliases: ['margarine spread'],
    serving: 'tbsp',
  },
  {
    name: 'yogurt',
    fdc: 171284,
    aliases: [
      'plain yogurt',
      'whole milk yogurt',
      'natural yogurt',
      'yoghurt',
      'plain yoghurt',
    ],
    serving: 'cup',
  },
  {
    name: 'low-fat yogurt',
    fdc: 170886,
    aliases: ['low fat yogurt', 'lowfat yogurt'],
    serving: 'cup',
  },
  {
    name: 'nonfat yogurt',
    fdc: 170887,
    aliases: ['fat-free yogurt', 'skim milk yogurt'],
    serving: 'cup',
  },
  {
    name: 'greek yogurt',
    fdc: 171304,
    aliases: ['greek yoghurt', 'whole milk greek yogurt', 'strained yogurt'],
    portions: { cup: 245 },
    serving: 'cup',
  },
  {
    name: 'nonfat greek yogurt',
    fdc: 170894,
    aliases: [
      '0% greek yogurt',
      'fat-free greek yogurt',
      'fat free greek yogurt',
    ],
    portions: { cup: 245 },
    serving: 'cup',
  },
  { name: 'vanilla yogurt', fdc: 170888, serving: 'cup' },
  {
    name: 'fruit yogurt',
    fdc: 170889,
    aliases: ['strawberry yogurt', 'flavored yogurt', 'fruit yoghurt'],
    serving: 'cup',
  },
  { name: 'frozen yogurt', fdc: 168105, aliases: ['froyo'], serving: 'cup' },
  { name: 'kefir', fdc: 170904, serving: 'cup', liquid: true },
  {
    name: 'cheddar',
    fdc: 173414,
    aliases: ['cheddar cheese', 'cheese'],
    serving: 'slice',
  },
  {
    name: 'mozzarella',
    fdc: 170845,
    aliases: ['mozzarella cheese', 'fresh mozzarella'],
    serving: 'slice',
  },
  {
    name: 'part-skim mozzarella',
    fdc: 171244,
    aliases: [
      'low-moisture mozzarella',
      'string cheese',
      'shredded mozzarella',
    ],
    serving: 'slice',
  },
  {
    name: 'parmesan',
    fdc: 171247,
    aliases: [
      'parmesan cheese',
      'parmigiano',
      'grated parmesan',
      'parmigiano reggiano',
    ],
    serving: 'tbsp',
  },
  {
    name: 'romano cheese',
    fdc: 171249,
    aliases: ['pecorino', 'pecorino romano'],
    portions: { tbsp: 5 },
    serving: 'tbsp',
  },
  {
    name: 'swiss cheese',
    fdc: 171251,
    aliases: ['emmental', 'emmentaler'],
    serving: 'slice',
  },
  {
    name: 'gruyere',
    fdc: 171242,
    aliases: ['gruyere cheese'],
    serving: 'slice',
  },
  { name: 'feta', fdc: 173420, aliases: ['feta cheese'], serving: 'cup' },
  { name: 'goat cheese', fdc: 173435, aliases: ['chevre', 'soft goat cheese'] },
  {
    name: 'brie',
    fdc: 172177,
    aliases: ['brie cheese'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'camembert',
    fdc: 172178,
    portions: { piece: 38 },
    serving: 'piece',
    servingLabel: 'wedge',
  },
  {
    name: 'gouda',
    fdc: 171241,
    aliases: ['gouda cheese'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'edam',
    fdc: 173419,
    aliases: ['edam cheese'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'provolone',
    fdc: 170850,
    aliases: ['provolone cheese'],
    serving: 'slice',
  },
  {
    name: 'monterey jack',
    fdc: 170844,
    aliases: ['jack cheese', 'monterey jack cheese'],
    serving: 'slice',
  },
  {
    name: 'colby',
    fdc: 173416,
    aliases: ['colby cheese', 'colby jack'],
    serving: 'slice',
  },
  {
    name: 'muenster',
    fdc: 171245,
    aliases: ['muenster cheese'],
    serving: 'slice',
  },
  { name: 'fontina', fdc: 170843, serving: 'slice' },
  {
    name: 'blue cheese',
    fdc: 172175,
    aliases: ['gorgonzola', 'stilton', 'roquefort'],
    portions: { tbsp: 8 },
    serving: 'tbsp',
  },
  {
    name: 'american cheese',
    fdc: 170853,
    aliases: ['processed cheese', 'cheese slice', 'burger cheese'],
    serving: 'slice',
  },
  { name: 'cottage cheese', fdc: 172179, serving: 'cup' },
  { name: 'ricotta', fdc: 170851, aliases: ['ricotta cheese'], serving: 'cup' },
  { name: 'queso fresco', fdc: 172223, serving: 'cup' },
  { name: 'cotija', fdc: 170898, aliases: ['cotija cheese'], serving: 'tsp' },
  {
    name: 'mexican cheese blend',
    fdc: 171288,
    aliases: ['shredded mexican cheese', 'taco cheese'],
    serving: 'cup',
  },
  {
    name: 'ice cream',
    fdc: 167575,
    aliases: ['vanilla ice cream'],
    portions: { cup: 132, piece: 66 },
    serving: 'piece',
    servingLabel: 'scoop',
  },
  {
    name: 'chocolate ice cream',
    fdc: 168809,
    portions: { piece: 66 },
    serving: 'piece',
    servingLabel: 'scoop',
  },
  {
    name: 'strawberry ice cream',
    fdc: 168810,
    portions: { piece: 66 },
    serving: 'piece',
    servingLabel: 'scoop',
  },
  {
    name: 'sherbet',
    fdc: 167577,
    aliases: ['sorbet', 'orange sherbet'],
    serving: 'piece',
    servingLabel: 'scoop',
  },
  {
    name: 'ice cream sandwich',
    fdc: 172226,
    portions: { piece: 70 },
    serving: 'piece',
  },
  {
    name: 'chocolate pudding',
    fdc: 168778,
    aliases: ['pudding', 'pudding cup'],
  },
  { name: 'eggnog', fdc: 171258, serving: 'cup', liquid: true },
  { name: 'dulce de leche', fdc: 173461, serving: 'tbsp' },
  {
    name: 'whey protein',
    fdc: 173180,
    aliases: [
      'protein powder',
      'whey protein powder',
      'whey',
      'protein shake',
      'protein drink',
      'whey shake',
    ],
    usdaPortions: false,
    portions: { piece: 30 },
    serving: 'piece',
    servingLabel: 'scoop',
  },
  { name: 'soy protein powder', fdc: 173181, usdaPortions: false },

  // Fats and oils
  {
    name: 'olive oil',
    fdc: 171413,
    aliases: ['extra virgin olive oil', 'evoo', 'virgin olive oil'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'canola oil',
    fdc: 172336,
    aliases: ['rapeseed oil'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'vegetable oil',
    fdc: 172370,
    aliases: ['soybean oil', 'cooking oil', 'oil'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'sunflower oil', fdc: 171025, serving: 'tbsp', liquid: true },
  { name: 'coconut oil', fdc: 171412, serving: 'tbsp', liquid: true },
  {
    name: 'sesame oil',
    fdc: 171016,
    aliases: ['toasted sesame oil'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'peanut oil',
    fdc: 171410,
    aliases: ['groundnut oil'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'avocado oil', fdc: 173573, serving: 'tbsp', liquid: true },
  {
    name: 'grapeseed oil',
    fdc: 171028,
    aliases: ['grape seed oil'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'walnut oil', fdc: 171030, serving: 'tbsp', liquid: true },
  {
    name: 'flaxseed oil',
    fdc: 167702,
    aliases: ['linseed oil', 'flax oil'],
    serving: 'tbsp',
    liquid: true,
  },
  { name: 'palm oil', fdc: 171015, serving: 'tbsp', liquid: true },
  { name: 'lard', fdc: 171401, serving: 'tbsp' },
  {
    name: 'shortening',
    fdc: 173584,
    aliases: ['vegetable shortening', 'crisco'],
    serving: 'tbsp',
  },
  {
    name: 'bacon grease',
    fdc: 172345,
    aliases: ['bacon fat', 'bacon dripping'],
    serving: 'tsp',
  },

  // Grains, flour, pasta, and bread
  {
    name: 'white rice',
    fdc: 168878,
    aliases: [
      'rice',
      'cooked rice',
      'cooked white rice',
      'long grain rice',
      'basmati rice',
      'jasmine rice',
      'steamed rice',
    ],
    serving: 'cup',
  },
  {
    name: 'uncooked rice',
    fdc: 168877,
    aliases: ['dry rice', 'raw rice', 'uncooked white rice', 'dry white rice'],
    serving: 'cup',
  },
  {
    name: 'brown rice',
    fdc: 169704,
    aliases: ['cooked brown rice'],
    serving: 'cup',
  },
  {
    name: 'uncooked brown rice',
    fdc: 169703,
    aliases: ['dry brown rice'],
    serving: 'cup',
  },
  { name: 'wild rice', fdc: 168897, serving: 'cup' },
  {
    name: 'sticky rice',
    fdc: 169711,
    aliases: ['glutinous rice', 'sushi rice'],
    serving: 'cup',
  },
  { name: 'quinoa', fdc: 168917, aliases: ['cooked quinoa'], serving: 'cup' },
  {
    name: 'uncooked quinoa',
    fdc: 168874,
    aliases: ['dry quinoa'],
    serving: 'cup',
  },
  { name: 'couscous', fdc: 169700, serving: 'cup' },
  {
    name: 'bulgur',
    fdc: 170287,
    aliases: ['bulgur wheat', 'burghul'],
    serving: 'cup',
  },
  {
    name: 'barley',
    fdc: 170285,
    aliases: ['pearl barley', 'pearled barley', 'cooked barley'],
    serving: 'cup',
  },
  {
    name: 'oats',
    fdc: 173904,
    aliases: [
      'rolled oats',
      'rolled oat',
      'porridge oats',
      'quick oats',
      'quick oat',
      'old-fashioned oats',
      'steel-cut oats',
      'steel cut oats',
    ],
    serving: 'cup',
  },
  {
    name: 'oatmeal',
    fdc: 173905,
    aliases: ['porridge', 'cooked oatmeal', 'cooked oats'],
    serving: 'cup',
  },
  {
    name: 'instant oatmeal',
    fdc: 171661,
    aliases: ['instant oats', 'oatmeal packet'],
    portions: { piece: 28 },
    serving: 'piece',
    servingLabel: 'packet',
  },
  { name: 'granola', fdc: 171646, serving: 'cup' },
  { name: 'cheerios', fdc: 173884, serving: 'cup' },
  {
    name: 'corn flakes',
    fdc: 174648,
    aliases: ['cornflakes', 'corn flake', 'cornflake'],
    serving: 'cup',
  },
  { name: 'raisin bran', fdc: 171650, serving: 'cup' },
  {
    name: 'frosted flakes',
    fdc: 172990,
    aliases: ['frosted flake', 'frosties'],
    serving: 'cup',
  },
  { name: 'shredded wheat', fdc: 173911, serving: 'cup' },
  { name: 'bran flakes', fdc: 173888, aliases: ['bran flake'], serving: 'cup' },
  {
    name: 'cream of wheat',
    fdc: 173901,
    aliases: ['farina', 'semolina porridge'],
    serving: 'tbsp',
  },
  {
    name: 'grits',
    fdc: 171672,
    aliases: ['corn grits', 'cooked grits'],
    serving: 'cup',
  },
  {
    name: 'flour',
    fdc: 168894,
    aliases: [
      'all-purpose flour',
      'all purpose flour',
      'white flour',
      'plain flour',
      'wheat flour',
      'ap flour',
    ],
    serving: 'cup',
  },
  {
    name: 'whole wheat flour',
    fdc: 168893,
    aliases: ['wholemeal flour', 'whole-wheat flour', 'wholewheat flour'],
    serving: 'cup',
  },
  {
    name: 'bread flour',
    fdc: 168896,
    aliases: ['strong flour', 'strong white flour'],
    serving: 'cup',
  },
  {
    name: 'self-rising flour',
    fdc: 168895,
    aliases: ['self-raising flour', 'self rising flour', 'self raising flour'],
    serving: 'cup',
  },
  { name: 'cake flour', fdc: 169723, serving: 'cup' },
  { name: 'rye flour', fdc: 168886, serving: 'cup' },
  { name: 'rice flour', fdc: 169714, serving: 'cup' },
  { name: 'brown rice flour', fdc: 168898, serving: 'cup' },
  {
    name: 'cornmeal',
    fdc: 169697,
    aliases: ['polenta', 'corn meal'],
    serving: 'cup',
  },
  {
    name: 'masa harina',
    fdc: 169694,
    aliases: ['masa', 'corn masa flour'],
    serving: 'cup',
  },
  { name: 'buckwheat flour', fdc: 170687, serving: 'cup' },
  {
    name: 'buckwheat',
    fdc: 170286,
    aliases: ['buckwheat groat', 'kasha'],
    serving: 'cup',
  },
  { name: 'millet', fdc: 168871, aliases: ['cooked millet'], serving: 'cup' },
  { name: 'amaranth', fdc: 170683, serving: 'cup' },
  {
    name: 'spelt',
    fdc: 169746,
    aliases: ['farro', 'cooked spelt'],
    serving: 'cup',
  },
  { name: 'teff', fdc: 168918, serving: 'cup' },
  { name: 'wheat germ', fdc: 168892, portions: { tbsp: 7 }, serving: 'tbsp' },
  { name: 'wheat bran', fdc: 169722, serving: 'cup' },
  { name: 'oat bran', fdc: 168872, serving: 'cup' },
  {
    name: 'wheat gluten',
    fdc: 168147,
    aliases: ['vital wheat gluten', 'seitan flour'],
  },
  {
    name: 'pasta',
    fdc: 169737,
    aliases: [
      'cooked pasta',
      'spaghetti',
      'penne',
      'macaroni',
      'fusilli',
      'rigatoni',
      'linguine',
      'fettuccine',
      'farfalle',
      'tagliatelle',
      'orzo',
      'noodle',
      'noodles',
    ],
    serving: 'cup',
  },
  {
    name: 'dry pasta',
    fdc: 169736,
    aliases: [
      'uncooked pasta',
      'dried pasta',
      'dry spaghetti',
      'uncooked spaghetti',
    ],
    serving: 'cup',
  },
  {
    name: 'whole wheat pasta',
    fdc: 168910,
    aliases: ['wholemeal pasta', 'whole grain pasta', 'whole-wheat pasta'],
    serving: 'cup',
  },
  { name: 'egg noodles', fdc: 169732, aliases: ['egg noodle'], serving: 'cup' },
  {
    name: 'rice noodles',
    fdc: 168914,
    aliases: [
      'rice noodle',
      'rice vermicelli',
      'pad thai noodle',
      'vermicelli',
    ],
    serving: 'cup',
  },
  {
    name: 'soba noodles',
    fdc: 168907,
    aliases: ['soba', 'soba noodle', 'buckwheat noodle'],
    serving: 'cup',
  },
  {
    name: 'chow mein noodles',
    fdc: 168905,
    aliases: ['chow mein noodle', 'crispy noodle'],
    serving: 'cup',
  },
  {
    name: 'gluten-free pasta',
    fdc: 168900,
    aliases: ['gluten free pasta', 'corn pasta'],
    serving: 'cup',
  },
  {
    name: 'tortellini',
    fdc: 172094,
    aliases: ['cheese tortellini'],
    serving: 'cup',
  },
  { name: 'ravioli', fdc: 173328, aliases: ['cheese ravioli'], serving: 'cup' },
  {
    name: 'lasagna',
    fdc: 173333,
    aliases: ['lasagne', 'frozen lasagna'],
    serving: 'cup',
  },
  {
    name: 'macaroni and cheese',
    fdc: 173342,
    aliases: ['mac and cheese', 'macaroni cheese', 'mac n cheese'],
    serving: 'cup',
  },
  {
    name: 'bread',
    fdc: 174924,
    aliases: ['white bread', 'sliced bread', 'sandwich bread', 'toast'],
    serving: 'slice',
  },
  {
    name: 'whole wheat bread',
    fdc: 172688,
    aliases: [
      'wholemeal bread',
      'brown bread',
      'whole-wheat bread',
      'wholewheat bread',
      'wheat bread',
    ],
    serving: 'slice',
  },
  {
    name: 'multigrain bread',
    fdc: 168013,
    aliases: [
      'whole grain bread',
      'multi-grain bread',
      'granary bread',
      'seeded bread',
    ],
    serving: 'slice',
  },
  { name: 'rye bread', fdc: 172684, serving: 'slice' },
  {
    name: 'pumpernickel',
    fdc: 174918,
    aliases: ['pumpernickel bread'],
    serving: 'slice',
  },
  {
    name: 'french bread',
    fdc: 172675,
    aliases: ['baguette', 'sourdough', 'sourdough bread', 'vienna bread'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'italian bread',
    fdc: 174913,
    aliases: ['ciabatta'],
    serving: 'slice',
  },
  { name: 'raisin bread', fdc: 172680, serving: 'slice' },
  {
    name: 'oat bran bread',
    fdc: 172676,
    aliases: ['oat bread'],
    serving: 'slice',
  },
  {
    name: 'sprouted bread',
    fdc: 171850,
    aliases: ['sprouted wheat bread', 'ezekiel bread'],
    serving: 'slice',
  },
  {
    name: 'pita',
    fdc: 174915,
    aliases: ['pita bread', 'pitta', 'pitta bread', 'white pita'],
  },
  {
    name: 'whole wheat pita',
    fdc: 174916,
    aliases: ['wholemeal pita', 'brown pita'],
  },
  { name: 'naan', fdc: 171845, aliases: ['naan bread'] },
  { name: 'bagel', fdc: 174899, aliases: ['plain bagel'] },
  { name: 'whole wheat bagel', fdc: 167533, aliases: ['wheat bagel'] },
  { name: 'cinnamon raisin bagel', fdc: 172664 },
  { name: 'english muffin', fdc: 174994 },
  {
    name: 'flour tortilla',
    fdc: 173242,
    aliases: [
      'tortilla',
      'wrap',
      'flour wrap',
      'burrito wrap',
      'soft tortilla',
    ],
  },
  { name: 'corn tortilla', fdc: 173241, aliases: ['taco tortilla'] },
  {
    name: 'taco shell',
    fdc: 172800,
    aliases: ['hard taco shell', 'hard shell taco'],
  },
  { name: 'croissant', fdc: 174987, aliases: ['butter croissant'] },
  {
    name: 'dinner roll',
    fdc: 172793,
    aliases: ['bread roll', 'roll', 'bun', 'white roll'],
  },
  {
    name: 'hamburger bun',
    fdc: 172796,
    aliases: [
      'burger bun',
      'hot dog bun',
      'hotdog bun',
      'hot dog roll',
      'burger roll',
    ],
  },
  {
    name: 'whole wheat bun',
    fdc: 174090,
    aliases: ['whole wheat hamburger bun', 'wholemeal bun', 'wholemeal roll'],
  },
  { name: 'kaiser roll', fdc: 175031, aliases: ['hard roll', 'crusty roll'] },
  { name: 'muffin', fdc: 172765, aliases: ['blueberry muffin'] },
  { name: 'corn muffin', fdc: 175002 },
  { name: 'pancake', fdc: 167926 },
  { name: 'waffle', fdc: 175038, aliases: ['frozen waffle'] },
  {
    name: 'cracker',
    fdc: 174982,
    aliases: ['ritz cracker', 'snack cracker', 'butter cracker'],
  },
  {
    name: 'saltine',
    fdc: 172746,
    aliases: ['saltine cracker', 'soda cracker'],
  },
  {
    name: 'whole wheat cracker',
    fdc: 172749,
    aliases: ['triscuit', 'wheat cracker'],
  },
  { name: 'graham cracker', fdc: 174957, aliases: ['digestive biscuit'] },
  {
    name: 'cheese cracker',
    fdc: 174975,
    aliases: ['goldfish cracker', 'goldfish', 'cheez-it'],
    serving: 'cup',
  },
  { name: 'rice cake', fdc: 168107, portions: { piece: 9 }, serving: 'piece' },
  { name: 'matzo', fdc: 172740, aliases: ['matzah', 'matzo cracker'] },
  {
    name: 'rye cracker',
    fdc: 172744,
    aliases: ['rye crispbread', 'crispbread', 'ryvita'],
  },
  { name: 'croutons', fdc: 172751, aliases: ['crouton'], serving: 'cup' },
  {
    name: 'bread crumbs',
    fdc: 174928,
    aliases: ['breadcrumbs', 'breadcrumb', 'panko', 'bread crumb'],
    portions: { tbsp: 7 },
    serving: 'tbsp',
  },
  {
    name: 'wonton wrapper',
    fdc: 172802,
    aliases: ['dumpling wrapper', 'egg roll wrapper'],
    usdaPortions: false,
    portions: { piece: 8 },
    serving: 'piece',
  },
  {
    name: 'phyllo dough',
    fdc: 172791,
    aliases: ['filo', 'filo pastry', 'phyllo', 'filo dough'],
    servingLabel: 'sheet',
  },
  {
    name: 'puff pastry',
    fdc: 172738,
    aliases: ['puff pastry sheet'],
    servingLabel: 'sheet',
  },

  // Sweets and baked treats
  {
    name: 'sugar',
    fdc: 169655,
    aliases: ['white sugar', 'granulated sugar', 'caster sugar', 'cane sugar'],
    serving: 'tsp',
  },
  {
    name: 'brown sugar',
    fdc: 168833,
    aliases: ['light brown sugar', 'dark brown sugar'],
    serving: 'tsp',
  },
  {
    name: 'powdered sugar',
    fdc: 169656,
    aliases: ['icing sugar', 'confectioners sugar', "confectioners' sugar"],
    serving: 'tbsp',
  },
  { name: 'honey', fdc: 169640, aliases: ['raw honey'], serving: 'tbsp' },
  {
    name: 'maple syrup',
    fdc: 169661,
    aliases: ['pure maple syrup'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'pancake syrup',
    fdc: 169578,
    aliases: ['table syrup', 'golden syrup'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'corn syrup',
    fdc: 168836,
    aliases: ['dark corn syrup'],
    serving: 'tbsp',
    liquid: true,
  },
  {
    name: 'molasses',
    fdc: 168820,
    aliases: ['treacle', 'black treacle'],
    portions: { tbsp: 20 },
    serving: 'tbsp',
  },
  {
    name: 'chocolate syrup',
    fdc: 168835,
    aliases: ['chocolate sauce', 'hot fudge'],
    serving: 'tbsp',
  },
  {
    name: 'caramel sauce',
    fdc: 168841,
    aliases: ['butterscotch sauce', 'caramel topping'],
    serving: 'tbsp',
  },
  {
    name: 'jam',
    fdc: 169641,
    aliases: [
      'preserve',
      'preserves',
      'strawberry jam',
      'fruit preserve',
      'raspberry jam',
      'apricot jam',
    ],
    serving: 'tbsp',
  },
  {
    name: 'jelly',
    fdc: 169642,
    aliases: ['grape jelly', 'fruit jelly'],
    portions: { tbsp: 21 },
    serving: 'tbsp',
  },
  {
    name: 'marmalade',
    fdc: 168819,
    aliases: ['orange marmalade'],
    serving: 'tbsp',
  },
  { name: 'apple butter', fdc: 168816, serving: 'tbsp' },
  {
    name: 'dark chocolate',
    fdc: 170273,
    aliases: ['70% chocolate', 'bittersweet chocolate', 'dark chocolate bar'],
    portions: { piece: 10 },
    serving: 'piece',
    servingLabel: 'square',
  },
  {
    name: 'semisweet chocolate',
    fdc: 170271,
    aliases: ['semi-sweet chocolate', '50% chocolate'],
    portions: { piece: 10 },
    serving: 'piece',
    servingLabel: 'square',
  },
  {
    name: 'milk chocolate',
    fdc: 167587,
    aliases: ['chocolate', 'chocolate bar', 'milk chocolate bar'],
    portions: { piece: 10 },
    serving: 'piece',
    servingLabel: 'square',
  },
  {
    name: 'white chocolate',
    fdc: 167571,
    portions: { piece: 10 },
    serving: 'piece',
    servingLabel: 'square',
  },
  {
    name: 'chocolate chips',
    fdc: 167976,
    aliases: ['chocolate chip', 'dark chocolate chip'],
    portions: { tbsp: 11 },
    serving: 'tbsp',
  },
  {
    name: 'baking chocolate',
    fdc: 167568,
    aliases: ['unsweetened chocolate', 'cooking chocolate', 'bakers chocolate'],
    portions: { piece: 29 },
    serving: 'piece',
    servingLabel: 'square',
  },
  {
    name: 'cocoa powder',
    fdc: 169593,
    aliases: ['cocoa', 'unsweetened cocoa', 'cacao powder', 'cacao'],
    serving: 'tbsp',
  },
  {
    name: 'hot cocoa mix',
    fdc: 174122,
    aliases: ['hot chocolate mix', 'cocoa mix', 'hot chocolate powder'],
    usdaPortions: false,
    portions: { piece: 28 },
    serving: 'piece',
    servingLabel: 'packet',
  },
  {
    name: 'hot chocolate',
    fdc: 171277,
    aliases: ['hot cocoa', 'cocoa drink'],
    serving: 'cup',
    liquid: true,
  },
  { name: 'caramel', fdc: 167974, aliases: ['caramel candy', 'toffee'] },
  {
    name: 'gummy candy',
    fdc: 167989,
    aliases: ['gummy', 'gummies', 'gummy bear', 'gumdrop', 'wine gum'],
    serving: 'piece',
  },
  { name: 'hard candy', fdc: 167990, aliases: ['boiled sweet', 'lollipop'] },
  {
    name: 'jelly beans',
    fdc: 167991,
    aliases: ['jelly bean', 'jellybean', 'jellybeans'],
    portions: { piece: 1.1 },
    serving: 'piece',
  },
  {
    name: 'marshmallow',
    fdc: 167995,
    usdaPortions: false,
    portions: { piece: 7.2, cup: 50 },
    serving: 'piece',
  },
  {
    name: 'chocolate covered peanuts',
    fdc: 168001,
    aliases: ['chocolate covered peanut', 'chocolate peanut'],
  },
  {
    name: 'chocolate covered raisins',
    fdc: 169576,
    aliases: ['chocolate covered raisin', 'chocolate raisin', 'raisinets'],
  },
  {
    name: 'chewing gum',
    fdc: 168771,
    aliases: ['gum', 'bubble gum'],
    usdaPortions: false,
    portions: { piece: 3 },
    serving: 'piece',
    servingLabel: 'stick',
  },
  {
    name: 'chocolate frosting',
    fdc: 168795,
    aliases: ['chocolate icing'],
    serving: 'tbsp',
  },
  {
    name: 'vanilla frosting',
    fdc: 169620,
    aliases: ['frosting', 'icing', 'vanilla icing', 'buttercream'],
    serving: 'tbsp',
  },
  {
    name: 'chocolate chip cookie',
    fdc: 172716,
    aliases: ['cookie', 'choc chip cookie'],
  },
  {
    name: 'oatmeal cookie',
    fdc: 172725,
    aliases: ['oat cookie', 'oatmeal raisin cookie'],
  },
  {
    name: 'shortbread',
    fdc: 174967,
    aliases: ['shortbread cookie', 'shortbread biscuit'],
  },
  { name: 'sugar cookie', fdc: 174971, aliases: ['vanilla cookie'] },
  { name: 'butter cookie', fdc: 174950, aliases: ['butter biscuit'] },
  {
    name: 'wafer cookie',
    fdc: 172736,
    aliases: ['sugar wafer', 'cream wafer', 'wafer'],
  },
  { name: 'brownie', fdc: 172713, portions: { piece: 56 }, serving: 'piece' },
  {
    name: 'chocolate cake',
    fdc: 174934,
    aliases: ['chocolate fudge cake'],
  },
  { name: 'pound cake', fdc: 174940, aliases: ['loaf cake', 'madeira cake'] },
  { name: 'sponge cake', fdc: 172706, aliases: ['victoria sponge', 'sponge'] },
  { name: 'angel food cake', fdc: 172694 },
  { name: 'cheesecake', fdc: 172711 },
  { name: 'apple pie', fdc: 175011 },
  { name: 'pumpkin pie', fdc: 172787 },
  { name: 'pecan pie', fdc: 175021 },
  {
    name: 'doughnut',
    fdc: 174990,
    aliases: ['donut', 'cake doughnut', 'cake donut'],
  },
  {
    name: 'glazed doughnut',
    fdc: 172758,
    aliases: ['glazed donut', 'krispy kreme', 'yeast doughnut', 'honey bun'],
    usdaPortions: false,
    portions: { piece: 60 },
    serving: 'piece',
  },
  {
    name: 'cinnamon roll',
    fdc: 167940,
    aliases: ['cinnamon bun', 'cinnamon swirl'],
  },
  { name: 'danish', fdc: 172754, aliases: ['danish pastry', 'cheese danish'] },
  {
    name: 'pizza',
    fdc: 170373,
    aliases: [
      'cheese pizza',
      'frozen pizza',
      'pizza slice',
      'margherita pizza',
    ],
    serving: 'slice',
  },
  {
    name: 'popsicle',
    fdc: 168813,
    aliases: ['ice pop', 'ice lolly', 'freezer pop'],
    usdaPortions: false,
    portions: { piece: 52 },
    serving: 'piece',
    servingLabel: 'pop',
  },
  {
    name: 'gelatin dessert',
    fdc: 169596,
    aliases: ['jello', 'jell-o', 'jelly dessert'],
    serving: 'cup',
  },

  // Legumes, nuts, seeds, and meat alternatives
  {
    name: 'black bean',
    fdc: 173735,
    aliases: ['cooked black bean', 'black turtle bean'],
    serving: 'cup',
  },
  {
    name: 'canned black bean',
    fdc: 175238,
    aliases: ['tinned black bean'],
    serving: 'cup',
  },
  {
    name: 'kidney bean',
    fdc: 173740,
    aliases: ['red kidney bean', 'cooked kidney bean'],
    serving: 'cup',
  },
  {
    name: 'canned kidney bean',
    fdc: 173741,
    aliases: ['tinned kidney bean'],
    serving: 'cup',
  },
  {
    name: 'pinto bean',
    fdc: 175200,
    aliases: ['cooked pinto bean'],
    serving: 'cup',
  },
  { name: 'canned pinto bean', fdc: 175201, serving: 'cup' },
  {
    name: 'navy bean',
    fdc: 173746,
    aliases: ['haricot bean', 'cooked navy bean'],
    serving: 'cup',
  },
  {
    name: 'white bean',
    fdc: 175203,
    aliases: ['cannellini bean', 'cannellini', 'butter bean'],
    serving: 'cup',
  },
  {
    name: 'canned white bean',
    fdc: 175204,
    aliases: ['canned cannellini bean', 'tinned cannellini bean'],
    serving: 'cup',
  },
  { name: 'great northern bean', fdc: 175191, serving: 'cup' },
  {
    name: 'black-eyed pea',
    fdc: 173759,
    aliases: ['black eyed pea', 'blackeye pea', 'cowpea'],
    serving: 'cup',
  },
  { name: 'lima bean', fdc: 174253, aliases: ['broad bean'], serving: 'cup' },
  {
    name: 'fava bean',
    fdc: 168574,
    aliases: ['faba bean', 'fresh fava bean'],
    serving: 'cup',
  },
  {
    name: 'mung bean',
    fdc: 174257,
    aliases: ['cooked mung bean', 'moong dal'],
    serving: 'cup',
  },
  {
    name: 'adzuki bean',
    fdc: 173728,
    aliases: ['azuki bean', 'red bean'],
    serving: 'cup',
  },
  {
    name: 'chickpea',
    fdc: 173757,
    aliases: [
      'garbanzo bean',
      'garbanzo',
      'chick pea',
      'cooked chickpea',
      'gram',
    ],
    serving: 'cup',
  },
  {
    name: 'canned chickpea',
    fdc: 173801,
    aliases: ['tinned chickpea', 'canned garbanzo bean'],
    serving: 'cup',
  },
  {
    name: 'dry chickpea',
    fdc: 173756,
    aliases: ['dried chickpea', 'uncooked chickpea'],
    serving: 'cup',
  },
  {
    name: 'dry black bean',
    fdc: 173734,
    aliases: ['dried black bean', 'uncooked black bean'],
    serving: 'cup',
  },
  {
    name: 'dry kidney bean',
    fdc: 175193,
    aliases: ['dried kidney bean', 'uncooked kidney bean'],
    serving: 'cup',
  },
  {
    name: 'dry pinto bean',
    fdc: 175199,
    aliases: ['dried pinto bean', 'uncooked pinto bean'],
    serving: 'cup',
  },
  {
    name: 'dry navy bean',
    fdc: 173745,
    aliases: ['dried navy bean', 'dried haricot bean'],
    serving: 'cup',
  },
  {
    name: 'lentil',
    fdc: 172421,
    aliases: ['cooked lentil', 'brown lentil', 'green lentil', 'red lentil'],
    serving: 'cup',
  },
  {
    name: 'dry lentil',
    fdc: 172420,
    aliases: ['dried lentil', 'uncooked lentil'],
    serving: 'cup',
  },
  {
    name: 'dry red lentil',
    fdc: 174284,
    aliases: ['split red lentil', 'masoor dal'],
    serving: 'cup',
  },
  {
    name: 'split pea',
    fdc: 172429,
    aliases: ['cooked split pea', 'yellow split pea', 'green split pea'],
    serving: 'cup',
  },
  { name: 'baked beans', fdc: 175182, aliases: ['baked bean'], serving: 'cup' },
  {
    name: 'refried beans',
    fdc: 172438,
    aliases: ['refried bean'],
    serving: 'cup',
  },
  {
    name: 'soybean',
    fdc: 174271,
    aliases: ['cooked soybean', 'soya bean'],
    serving: 'cup',
  },
  {
    name: 'roasted soybean',
    fdc: 174300,
    aliases: ['soy nut', 'roasted soy nut'],
    serving: 'cup',
  },
  {
    name: 'soy milk',
    fdc: 172456,
    aliases: ['soymilk', 'soya milk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'unsweetened soy milk',
    fdc: 175215,
    aliases: ['unsweetened soymilk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'almond milk',
    fdc: 174832,
    aliases: ['unsweetened almond milk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'sweetened almond milk',
    fdc: 168751,
    aliases: ['vanilla almond milk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'oat milk',
    fdc: 2257046,
    aliases: ['oatmilk', 'oat drink'],
    portions: { cup: 240 },
    serving: 'cup',
    liquid: true,
  },
  { name: 'rice milk', fdc: 171942, serving: 'cup', liquid: true },
  {
    name: 'coconut milk',
    fdc: 170173,
    aliases: ['canned coconut milk', 'coconut cream'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'coconut milk beverage',
    fdc: 174116,
    aliases: ['coconut milk drink', 'carton coconut milk'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'tofu',
    fdc: 172448,
    aliases: ['firm tofu', 'bean curd'],
    serving: 'cup',
    servingLabel: 'cup',
  },
  { name: 'soft tofu', fdc: 172449, aliases: ['silken tofu'], serving: 'cup' },
  {
    name: 'extra firm tofu',
    fdc: 174290,
    aliases: ['extra-firm tofu'],
    usdaPortions: false,
    portions: { piece: 455, cup: 252 },
    serving: 'cup',
  },
  { name: 'fried tofu', fdc: 172451, aliases: ['tofu puff'] },
  { name: 'tempeh', fdc: 174272, serving: 'cup' },
  { name: 'falafel', fdc: 172455, aliases: ['falafel ball'] },
  {
    name: 'veggie burger',
    fdc: 169888,
    aliases: [
      'vegetarian burger',
      'veggie patty',
      'meatless burger',
      'plant-based burger',
    ],
    usdaPortions: false,
    portions: { piece: 56 },
    serving: 'piece',
    servingLabel: 'patty',
  },
  {
    name: 'meatless chicken',
    fdc: 167719,
    aliases: [
      'vegetarian chicken',
      'plant-based chicken',
      'chicken substitute',
    ],
    serving: 'cup',
  },
  {
    name: 'peanut',
    fdc: 172430,
    aliases: ['raw peanut', 'groundnut', 'monkey nut'],
  },
  {
    name: 'roasted peanut',
    fdc: 173806,
    aliases: ['dry roasted peanut', 'salted peanut'],
    class: 'nuts',
  },
  {
    name: 'peanut butter',
    fdc: 174294,
    aliases: ['smooth peanut butter', 'creamy peanut butter', 'pb'],
    serving: 'tbsp',
  },
  {
    name: 'crunchy peanut butter',
    fdc: 172469,
    aliases: ['chunky peanut butter'],
    serving: 'tbsp',
  },
  {
    name: 'almond',
    fdc: 170567,
    aliases: ['raw almond', 'whole almond'],
  },
  {
    name: 'roasted almond',
    fdc: 170158,
    aliases: ['dry roasted almond', 'toasted almond'],
    class: 'nuts',
  },
  {
    name: 'sliced almond',
    fdc: 170567,
    aliases: ['flaked almond', 'almond flake', 'slivered almond'],
    usdaPortions: false,
    portions: { cup: 92, tbsp: 6 },
    serving: 'tbsp',
  },
  { name: 'almond butter', fdc: 168588, serving: 'tbsp' },
  { name: 'almond paste', fdc: 170160, aliases: ['marzipan'] },
  {
    name: 'cashew',
    fdc: 170571,
    aliases: [
      'roasted cashew',
      'cashew nut',
      'salted cashew',
      'dry roasted cashew',
    ],
  },
  { name: 'raw cashew', fdc: 170162 },
  { name: 'cashew butter', fdc: 170163, serving: 'tbsp' },
  {
    name: 'walnut',
    fdc: 170187,
    aliases: ['english walnut', 'walnut half', 'walnut piece'],
    portions: { piece: 2 },
  },
  {
    name: 'pecan',
    fdc: 170182,
    aliases: ['pecan half', 'pecan nut'],
    portions: { piece: 1.5 },
  },
  {
    name: 'pistachio',
    fdc: 170184,
    aliases: ['pistachio nut', 'raw pistachio'],
  },
  {
    name: 'roasted pistachio',
    fdc: 170185,
    aliases: ['salted pistachio'],
    class: 'nuts',
  },
  { name: 'hazelnut', fdc: 170581, aliases: ['filbert'] },
  {
    name: 'macadamia',
    fdc: 170178,
    aliases: ['macadamia nut'],
  },
  { name: 'brazil nut', fdc: 170569, class: 'nuts' },
  {
    name: 'pine nut',
    fdc: 170591,
    aliases: ['pignoli', 'pinon'],
    class: 'nuts',
  },
  {
    name: 'chestnut',
    fdc: 170190,
    aliases: ['roasted chestnut'],
    serving: 'cup',
  },
  {
    name: 'mixed nuts',
    fdc: 170585,
    aliases: ['mixed nut', 'nut mix'],
    class: 'nuts',
  },
  { name: 'trail mix', fdc: 167561, class: 'nuts' },
  {
    name: 'sunflower seed',
    fdc: 170562,
    aliases: ['sunflower kernel'],
    portions: { cup: 140, tbsp: 9 },
  },
  {
    name: 'roasted sunflower seed',
    fdc: 170563,
    aliases: ['salted sunflower seed'],
    portions: { tbsp: 8 },
    class: 'seeds',
  },
  {
    name: 'sunflower seed butter',
    fdc: 170155,
    aliases: ['sunbutter'],
    serving: 'tbsp',
  },
  {
    name: 'pumpkin seed',
    fdc: 170556,
    aliases: ['pepita', 'pumpkin seed kernel'],
    portions: { tbsp: 8 },
  },
  {
    name: 'roasted pumpkin seed',
    fdc: 170557,
    aliases: ['roasted pepita'],
    portions: { tbsp: 7 },
    class: 'seeds',
  },
  { name: 'sesame seed', fdc: 170150, aliases: ['sesame'] },
  {
    name: 'flaxseed',
    fdc: 169414,
    aliases: ['flax seed', 'linseed', 'ground flaxseed', 'flax meal'],
  },
  {
    name: 'chia seed',
    fdc: 170554,
    aliases: ['chia'],
    portions: { tbsp: 12 },
  },
  {
    name: 'hemp seed',
    fdc: 170148,
    aliases: ['hemp heart', 'hulled hemp seed'],
  },

  // Meat
  {
    name: 'ground beef',
    fdc: 174036,
    aliases: [
      'minced beef',
      'beef mince',
      'hamburger meat',
      'ground beef 80/20',
      '80/20 ground beef',
      'mince',
    ],
  },
  {
    name: 'lean ground beef',
    fdc: 174030,
    aliases: [
      'ground beef 90/10',
      '90/10 ground beef',
      'lean beef mince',
      'lean mince',
    ],
  },
  {
    name: 'extra lean ground beef',
    fdc: 171790,
    aliases: ['ground beef 95/5', '95/5 ground beef', 'extra lean beef mince'],
  },
  {
    name: 'ground beef 85/15',
    fdc: 171796,
    aliases: ['85/15 ground beef', 'ground beef 85% lean'],
  },
  {
    name: 'ground beef 93/7',
    fdc: 173110,
    aliases: ['93/7 ground beef', 'ground beef 93% lean'],
  },
  {
    name: 'ground beef 70/30',
    fdc: 168652,
    aliases: ['70/30 ground beef', 'regular ground beef'],
  },
  {
    name: 'ribeye',
    fdc: 173402,
    aliases: ['ribeye steak', 'rib eye', 'rib eye steak', 'scotch fillet'],
    servingLabel: 'steak',
  },
  {
    name: 'sirloin steak',
    fdc: 168726,
    aliases: ['top sirloin', 'sirloin', 'top sirloin steak', 'rump steak'],
    usdaPortions: false,
  },
  {
    name: 'strip steak',
    fdc: 171750,
    aliases: [
      'new york strip',
      'ny strip',
      'top loin steak',
      'striploin',
      'porterhouse',
    ],
    servingLabel: 'steak',
  },
  {
    name: 't-bone steak',
    fdc: 172118,
    aliases: ['t-bone', 'tbone steak'],
    servingLabel: 'steak',
  },
  {
    name: 'beef tenderloin',
    fdc: 169542,
    aliases: [
      'filet mignon',
      'tenderloin steak',
      'fillet steak',
      'beef fillet',
      'eye fillet',
    ],
    servingLabel: 'steak',
  },
  {
    name: 'flank steak',
    fdc: 169563,
    aliases: ['flank', 'bavette'],
    servingLabel: 'steak',
  },
  {
    name: 'top round steak',
    fdc: 169529,
    aliases: ['round steak', 'london broil', 'topside'],
  },
  {
    name: 'eye of round',
    fdc: 169523,
    aliases: ['eye of round roast', 'eye round'],
  },
  {
    name: 'chuck roast',
    fdc: 169491,
    aliases: ['pot roast', 'beef chuck', 'chuck pot roast', 'arm roast'],
  },
  {
    name: 'blade roast',
    fdc: 169493,
    aliases: ['chuck blade roast', 'blade steak'],
  },
  {
    name: 'beef stew meat',
    fdc: 171206,
    aliases: [
      'stew meat',
      'stewing beef',
      'beef chunk',
      'diced beef',
      'stew beef',
    ],
  },
  { name: 'brisket', fdc: 168664, aliases: ['beef brisket'] },
  { name: 'short ribs', fdc: 170826, aliases: ['short rib', 'beef short rib'] },
  {
    name: 'prime rib',
    fdc: 169509,
    aliases: ['rib roast', 'standing rib roast', 'beef rib'],
  },
  {
    name: 'corned beef',
    fdc: 170199,
    aliases: ['salt beef', 'corned beef brisket'],
  },
  { name: 'beef liver', fdc: 169451, aliases: ['liver'] },
  { name: 'ground pork', fdc: 167902, aliases: ['minced pork', 'pork mince'] },
  {
    name: 'pork chop',
    fdc: 167839,
    aliases: ['pork loin chop', 'boneless pork chop', 'pork cutlet'],
    servingLabel: 'chop',
  },
  {
    name: 'pork tenderloin',
    fdc: 168312,
    aliases: ['pork fillet', 'pork loin fillet'],
  },
  {
    name: 'pork loin',
    fdc: 167818,
    aliases: ['pork loin roast', 'pork roast'],
    servingLabel: 'chop',
  },
  {
    name: 'pork shoulder',
    fdc: 167843,
    aliases: [
      'pork butt',
      'boston butt',
      'picnic shoulder',
      'pulled pork meat',
    ],
  },
  { name: 'pork belly', fdc: 167812 },
  {
    name: 'spare ribs',
    fdc: 167853,
    aliases: [
      'spare rib',
      'pork rib',
      'spareribs',
      'pork spare rib',
      'rib',
      'ribs',
    ],
  },
  {
    name: 'baby back ribs',
    fdc: 168299,
    aliases: ['baby back rib', 'back rib', 'pork back rib'],
  },
  { name: 'fresh ham', fdc: 168222, aliases: ['pork leg', 'leg of pork'] },
  {
    name: 'ham',
    fdc: 167872,
    aliases: ['cooked ham', 'roast ham', 'ham roast'],
    serving: 'cup',
  },
  {
    name: 'sliced ham',
    fdc: 173864,
    aliases: ['deli ham', 'ham slice', 'lunch ham', 'sandwich ham'],
    serving: 'slice',
  },
  {
    name: 'bacon',
    fdc: 168277,
    aliases: ['raw bacon', 'streaky bacon', 'bacon rasher', 'bacon strip'],
    serving: 'slice',
  },
  {
    name: 'cooked bacon',
    fdc: 168322,
    aliases: ['crispy bacon', 'fried bacon'],
    serving: 'slice',
  },
  { name: 'turkey bacon', fdc: 174592, serving: 'slice' },
  {
    name: 'lamb chop',
    fdc: 172551,
    aliases: ['lamb loin chop', 'lamb loin'],
    servingLabel: 'chop',
  },
  { name: 'ground lamb', fdc: 174370, aliases: ['minced lamb', 'lamb mince'] },
  { name: 'leg of lamb', fdc: 174372, aliases: ['lamb leg', 'lamb roast'] },
  { name: 'lamb shoulder', fdc: 172553 },
  { name: 'rack of lamb', fdc: 174377, aliases: ['lamb rib', 'lamb rack'] },
  { name: 'lamb shank', fdc: 172547, aliases: ['lamb foreshank'] },
  {
    name: 'veal',
    fdc: 175268,
    aliases: ['veal leg', 'veal cutlet', 'veal escalope', 'veal top round'],
  },
  { name: 'ground veal', fdc: 175290, aliases: ['minced veal', 'veal mince'] },
  { name: 'veal loin', fdc: 173823, aliases: ['veal chop'] },
  {
    name: 'venison',
    fdc: 173855,
    aliases: ['deer meat', 'deer', 'venison steak'],
  },
  {
    name: 'ground venison',
    fdc: 172602,
    aliases: ['minced venison', 'venison mince', 'ground deer'],
  },
  { name: 'bison', fdc: 173851, aliases: ['buffalo meat', 'bison steak'] },
  {
    name: 'ground bison',
    fdc: 174421,
    aliases: ['bison mince', 'ground buffalo'],
  },
  { name: 'elk', fdc: 175301, aliases: ['elk meat'] },
  { name: 'rabbit', fdc: 172521, aliases: ['rabbit meat'] },
  { name: 'goat', fdc: 175303, aliases: ['goat meat'] },
  {
    name: 'chicken breast',
    fdc: 171077,
    aliases: [
      'boneless skinless chicken breast',
      'skinless chicken breast',
      'chicken breast fillet',
      'chicken fillet',
    ],
    servingLabel: 'breast',
  },
  {
    name: 'chicken breast with skin',
    fdc: 171474,
    aliases: ['bone-in chicken breast', 'skin-on chicken breast'],
    servingLabel: 'breast',
  },
  {
    name: 'cooked chicken breast',
    fdc: 171477,
    aliases: [
      'roasted chicken breast',
      'grilled chicken breast',
      'grilled chicken',
      'cooked chicken',
      'shredded chicken',
      'roast chicken breast',
    ],
    serving: 'cup',
  },
  {
    name: 'rotisserie chicken',
    fdc: 171125,
    aliases: ['roast chicken', 'roasted chicken', 'rotisserie chicken breast'],
    usdaPortions: false,
  },
  {
    name: 'chicken thigh',
    fdc: 173627,
    aliases: [
      'boneless skinless chicken thigh',
      'skinless chicken thigh',
      'boneless chicken thigh',
      'chicken thigh fillet',
    ],
    servingLabel: 'thigh',
  },
  {
    name: 'chicken thigh with skin',
    fdc: 172385,
    aliases: ['bone-in chicken thigh', 'skin-on chicken thigh'],
    servingLabel: 'thigh',
  },
  {
    name: 'chicken drumstick',
    fdc: 172373,
    aliases: ['drumstick', 'chicken leg'],
    servingLabel: 'drumstick',
  },
  {
    name: 'chicken leg quarter',
    fdc: 172378,
    aliases: ['chicken leg with skin', 'whole chicken leg', 'leg quarter'],
  },
  {
    name: 'chicken wing',
    fdc: 172390,
    aliases: ['wing', 'buffalo wing'],
    servingLabel: 'wing',
  },
  {
    name: 'whole chicken',
    fdc: 171447,
    aliases: ['chicken whole', 'roasting chicken', 'broiler chicken'],
    usdaPortions: false,
  },
  {
    name: 'ground chicken',
    fdc: 171116,
    aliases: ['minced chicken', 'chicken mince'],
  },
  { name: 'chicken liver', fdc: 171060 },
  {
    name: 'chicken nuggets',
    fdc: 172112,
    aliases: ['chicken nugget', 'nugget', 'nuggets', 'chicken tender'],
    servingLabel: 'nugget',
  },
  {
    name: 'cornish hen',
    fdc: 171507,
    aliases: ['cornish game hen', 'poussin', 'spatchcock'],
  },
  {
    name: 'turkey breast',
    fdc: 174515,
    aliases: [
      'boneless turkey breast',
      'turkey breast fillet',
      'turkey steak',
      'turkey',
    ],
    usdaPortions: false,
  },
  {
    name: 'turkey breast with skin',
    fdc: 171528,
    aliases: ['bone-in turkey breast', 'turkey crown'],
    usdaPortions: false,
  },
  {
    name: 'sliced turkey',
    fdc: 172941,
    aliases: [
      'deli turkey',
      'turkey slice',
      'turkey lunch meat',
      'sliced turkey breast',
      'deli turkey breast',
    ],
    serving: 'slice',
  },
  {
    name: 'ground turkey',
    fdc: 171505,
    aliases: ['minced turkey', 'turkey mince'],
    servingLabel: 'patty',
  },
  {
    name: 'turkey drumstick',
    fdc: 171134,
    aliases: ['turkey leg'],
    servingLabel: 'drumstick',
  },
  { name: 'turkey thigh', fdc: 171533, servingLabel: 'thigh' },
  {
    name: 'whole turkey',
    fdc: 171081,
    aliases: ['turkey whole'],
    usdaPortions: false,
    portions: { piece: 5002 },
    serving: 'piece',
    servingLabel: 'bird',
  },
  {
    name: 'duck',
    fdc: 172408,
    aliases: ['whole duck', 'duck meat', 'duck with skin'],
    servingLabel: 'bird',
  },
  {
    name: 'duck breast',
    fdc: 172410,
    aliases: ['skinless duck breast', 'duck meat only'],
    usdaPortions: false,
  },
  {
    name: 'goose',
    fdc: 174470,
    aliases: ['whole goose', 'goose meat'],
    servingLabel: 'bird',
  },
  {
    name: 'quail',
    fdc: 172418,
    aliases: ['whole quail'],
    servingLabel: 'bird',
  },
  { name: 'pheasant', fdc: 174472, servingLabel: 'bird' },

  // Deli meats and sausages
  {
    name: 'hot dog',
    fdc: 173862,
    aliases: ['hotdog', 'frankfurter', 'wiener', 'beef hot dog', 'frank'],
  },
  {
    name: 'chicken hot dog',
    fdc: 171624,
    aliases: ['chicken frankfurter', 'chicken frank'],
  },
  {
    name: 'turkey hot dog',
    fdc: 171625,
    aliases: ['turkey frankfurter', 'turkey frank'],
  },
  {
    name: 'italian sausage',
    fdc: 171631,
    aliases: [
      'pork sausage link',
      'sausage',
      'italian pork sausage',
      'sausage link',
    ],
    servingLabel: 'link',
  },
  {
    name: 'breakfast sausage',
    fdc: 172934,
    aliases: [
      'pork sausage',
      'sausage patty',
      'breakfast link',
      'sausage meat',
    ],
    servingLabel: 'link',
  },
  { name: 'bratwurst', fdc: 171622, aliases: ['brat'], servingLabel: 'link' },
  {
    name: 'kielbasa',
    fdc: 173879,
    aliases: ['polish sausage', 'smoked sausage', 'polska kielbasa'],
    servingLabel: 'ring',
  },
  {
    name: 'chorizo',
    fdc: 173859,
    aliases: ['mexican chorizo', 'chorizo sausage'],
    servingLabel: 'link',
  },
  {
    name: 'turkey sausage',
    fdc: 174600,
    aliases: ['turkey breakfast sausage', 'turkey link'],
    servingLabel: 'link',
  },
  {
    name: 'chicken sausage',
    fdc: 174605,
    aliases: ['chicken sausage link'],
    servingLabel: 'link',
  },
  {
    name: 'salami',
    fdc: 172938,
    aliases: ['italian salami', 'genoa salami', 'hard salami', 'dry salami'],
    serving: 'slice',
  },
  {
    name: 'beef salami',
    fdc: 172935,
    aliases: ['cooked salami', 'cotto salami'],
    serving: 'slice',
  },
  {
    name: 'pepperoni',
    fdc: 174575,
    aliases: ['pepperoni slice'],
    servingLabel: 'slice',
  },
  {
    name: 'bologna',
    fdc: 172013,
    aliases: ['baloney', 'polony', 'luncheon meat'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'mortadella',
    fdc: 174573,
    portions: { slice: 15 },
    serving: 'slice',
  },
  {
    name: 'liverwurst',
    fdc: 174596,
    aliases: ['liver pate', 'liver sausage', 'braunschweiger'],
    serving: 'cup',
  },
  {
    name: 'pastrami',
    fdc: 170204,
    aliases: ['beef pastrami'],
    serving: 'slice',
  },
  {
    name: 'turkey pastrami',
    fdc: 172927,
    serving: 'slice',
  },
  {
    name: 'roast beef',
    fdc: 174570,
    aliases: ['deli roast beef', 'sliced roast beef', 'roast beef slice'],
    serving: 'slice',
  },
  {
    name: 'deli chicken',
    fdc: 173874,
    aliases: [
      'sliced chicken breast',
      'chicken lunch meat',
      'deli chicken breast',
      'chicken slice',
    ],
    serving: 'slice',
  },
  {
    name: 'canned corned beef',
    fdc: 170602,
    aliases: ['corned beef can', 'tinned corned beef'],
    serving: 'slice',
  },
  {
    name: 'spam',
    fdc: 174571,
    aliases: ['canned pork', 'canned luncheon meat'],
    serving: 'slice',
  },
  { name: 'beef jerky', fdc: 167536, aliases: ['jerky'] },

  // Fish and seafood
  {
    name: 'salmon',
    fdc: 175167,
    aliases: [
      'atlantic salmon',
      'farmed salmon',
      'salmon fillet',
      'fresh salmon',
    ],
    usdaPortions: false,
    portions: { piece: 198 },
    serving: 'piece',
    servingLabel: 'fillet',
  },
  {
    name: 'wild salmon',
    fdc: 173686,
    aliases: ['wild atlantic salmon'],
    usdaPortions: false,
    portions: { piece: 198 },
    serving: 'piece',
    servingLabel: 'fillet',
  },
  {
    name: 'sockeye salmon',
    fdc: 173691,
    aliases: ['red salmon', 'wild sockeye'],
    usdaPortions: false,
    portions: { piece: 198 },
    serving: 'piece',
    servingLabel: 'fillet',
  },
  {
    name: 'canned salmon',
    fdc: 175175,
    aliases: ['tinned salmon', 'pink salmon'],
  },
  {
    name: 'smoked salmon',
    fdc: 173687,
    aliases: ['lox', 'gravlax', 'cold smoked salmon'],
    portions: { slice: 28 },
    serving: 'slice',
  },
  {
    name: 'tuna',
    fdc: 175159,
    aliases: ['tuna steak', 'yellowfin tuna', 'ahi tuna', 'fresh tuna', 'ahi'],
  },
  { name: 'bluefin tuna', fdc: 173706, aliases: ['sushi tuna', 'maguro'] },
  {
    name: 'canned tuna',
    fdc: 173709,
    aliases: [
      'tuna in water',
      'tinned tuna',
      'light tuna',
      'chunk light tuna',
      'tuna can',
    ],
    portions: { piece: 165 },
    serving: 'piece',
    servingLabel: 'can',
  },
  {
    name: 'canned tuna in oil',
    fdc: 173708,
    aliases: ['tuna in oil', 'tinned tuna in oil'],
    portions: { piece: 171 },
    serving: 'piece',
    servingLabel: 'can',
  },
  {
    name: 'albacore tuna',
    fdc: 175158,
    aliases: [
      'white tuna',
      'canned white tuna',
      'canned albacore',
      'solid white tuna',
    ],
    portions: { piece: 172 },
    serving: 'piece',
    servingLabel: 'can',
  },
  {
    name: 'cod',
    fdc: 171955,
    aliases: ['atlantic cod', 'cod fillet', 'fresh cod', 'cod loin'],
    servingLabel: 'fillet',
  },
  {
    name: 'pacific cod',
    fdc: 174191,
    aliases: ['alaskan cod', 'frozen cod'],
    servingLabel: 'fillet',
  },
  {
    name: 'haddock',
    fdc: 171964,
    aliases: ['haddock fillet'],
    servingLabel: 'fillet',
  },
  {
    name: 'pollock',
    fdc: 175130,
    aliases: ['alaska pollock', 'pollack'],
    servingLabel: 'fillet',
  },
  {
    name: 'tilapia',
    fdc: 175176,
    aliases: ['tilapia fillet'],
    servingLabel: 'fillet',
  },
  {
    name: 'halibut',
    fdc: 174200,
    aliases: ['halibut fillet', 'halibut steak'],
    usdaPortions: false,
    portions: { piece: 204 },
    serving: 'piece',
    servingLabel: 'fillet',
  },
  {
    name: 'trout',
    fdc: 173717,
    aliases: ['rainbow trout', 'trout fillet'],
    servingLabel: 'fillet',
  },
  {
    name: 'mackerel',
    fdc: 175119,
    aliases: ['atlantic mackerel', 'fresh mackerel'],
    servingLabel: 'fillet',
  },
  {
    name: 'sardine',
    fdc: 175139,
    aliases: ['canned sardine', 'tinned sardine'],
    usdaPortions: false,
    portions: { cup: 149, piece: 12 },
    serving: 'piece',
  },
  {
    name: 'anchovy',
    fdc: 174183,
    aliases: ['canned anchovy', 'anchovy fillet'],
  },
  {
    name: 'herring',
    fdc: 175116,
    aliases: ['atlantic herring', 'fresh herring'],
    servingLabel: 'fillet',
  },
  {
    name: 'pickled herring',
    fdc: 175118,
    aliases: ['rollmop', 'herring in brine'],
    serving: 'cup',
  },
  {
    name: 'swordfish',
    fdc: 173703,
    aliases: ['swordfish steak'],
    servingLabel: 'steak',
  },
  {
    name: 'sea bass',
    fdc: 175142,
    aliases: ['bass', 'branzino'],
    servingLabel: 'fillet',
  },
  {
    name: 'snapper',
    fdc: 173698,
    aliases: ['red snapper'],
    servingLabel: 'fillet',
  },
  { name: 'grouper', fdc: 171962, servingLabel: 'fillet' },
  {
    name: 'mahi mahi',
    fdc: 171959,
    aliases: ['mahi-mahi', 'mahimahi', 'dorado'],
    servingLabel: 'fillet',
  },
  {
    name: 'catfish',
    fdc: 175165,
    aliases: ['catfish fillet'],
    servingLabel: 'fillet',
  },
  {
    name: 'flounder',
    fdc: 174196,
    aliases: ['sole', 'flatfish', 'sole fillet', 'plaice'],
    servingLabel: 'fillet',
  },
  {
    name: 'whitefish',
    fdc: 173711,
    aliases: ['white fish', 'lake whitefish'],
    servingLabel: 'fillet',
  },
  {
    name: 'fish sticks',
    fdc: 174195,
    aliases: ['fish stick', 'fish fingers', 'fish finger'],
    usdaPortions: false,
    portions: { piece: 28 },
    serving: 'piece',
    servingLabel: 'stick',
  },
  {
    name: 'shrimp',
    fdc: 174210,
    aliases: ['prawn', 'raw shrimp', 'king prawn', 'jumbo shrimp'],
    serving: 'large',
  },
  {
    name: 'crab',
    fdc: 174204,
    aliases: ['blue crab', 'crab meat', 'crabmeat'],
  },
  {
    name: 'king crab',
    fdc: 175164,
    aliases: ['alaskan king crab', 'king crab leg', 'crab leg'],
    servingLabel: 'leg',
  },
  { name: 'dungeness crab', fdc: 171968 },
  {
    name: 'lobster',
    fdc: 174208,
    aliases: ['whole lobster', 'lobster tail', 'lobster meat'],
  },
  { name: 'crayfish', fdc: 175169, aliases: ['crawfish', 'crawdad', 'yabby'] },
  { name: 'mussel', fdc: 174216, aliases: ['blue mussel'], serving: 'cup' },
  { name: 'clam', fdc: 174214, aliases: ['littleneck clam', 'fresh clam'] },
  { name: 'oyster', fdc: 171978, aliases: ['eastern oyster', 'raw oyster'] },
  {
    name: 'scallop',
    fdc: 174220,
    aliases: ['sea scallop', 'bay scallop'],
    usdaPortions: false,
    portions: { large: 15, piece: 15 },
    serving: 'piece',
  },
  { name: 'squid', fdc: 174223, aliases: ['calamari'] },
  { name: 'octopus', fdc: 174218 },

  // Snacks and prepared items
  {
    name: 'potato chips',
    fdc: 169677,
    aliases: ['potato chip', 'crisps', 'crisp'],
    portions: { cup: 28 },
    serving: 'cup',
  },
  {
    name: 'tortilla chips',
    fdc: 167558,
    aliases: [
      'tortilla chip',
      'corn chips',
      'corn chip',
      'nachos',
      'nacho chip',
    ],
    usdaPortions: false,
    portions: { cup: 28 },
    serving: 'cup',
  },
  {
    name: 'cheese puffs',
    fdc: 167537,
    aliases: [
      'cheetos',
      'cheese curls',
      'cheese curl',
      'corn puffs',
      'cheese puff',
    ],
    usdaPortions: false,
    portions: { cup: 28 },
    serving: 'cup',
  },
  {
    name: 'pretzel',
    fdc: 167555,
    aliases: ['hard pretzel', 'pretzel twist', 'salted pretzel'],
  },
  { name: 'soft pretzel', fdc: 169064 },
  {
    name: 'popcorn',
    fdc: 167959,
    aliases: ['air-popped popcorn', 'plain popcorn', 'air popped popcorn'],
    serving: 'cup',
  },
  {
    name: 'microwave popcorn',
    fdc: 173141,
    aliases: ['butter popcorn', 'buttered popcorn', 'movie popcorn'],
    serving: 'cup',
  },
  {
    name: 'caramel popcorn',
    fdc: 169685,
    aliases: ['kettle corn', 'toffee popcorn'],
  },
  {
    name: 'pita chips',
    fdc: 173147,
    aliases: ['pita chip'],
    usdaPortions: false,
    portions: { cup: 28 },
    serving: 'cup',
  },
  {
    name: 'veggie chips',
    fdc: 174791,
    aliases: [
      'vegetable chips',
      'vegetable chip',
      'veggie chip',
      'terra chips',
    ],
    usdaPortions: false,
    portions: { cup: 28 },
    serving: 'cup',
  },
  {
    name: 'banana chips',
    fdc: 168849,
    aliases: ['banana chip', 'dried banana'],
  },
  {
    name: 'granola bar',
    fdc: 167954,
    aliases: ['cereal bar', 'oat bar', 'chewy granola bar'],
    servingLabel: 'bar',
  },
  {
    name: 'crunchy granola bar',
    fdc: 167542,
    aliases: ['nature valley bar', 'hard granola bar'],
    servingLabel: 'bar',
  },
  {
    name: 'rice krispie treat',
    fdc: 167951,
    aliases: ['crisped rice bar', 'rice crispy treat', 'rice krispies treat'],
    servingLabel: 'bar',
  },
  {
    name: 'pork rinds',
    fdc: 167961,
    aliases: [
      'pork rind',
      'pork scratchings',
      'pork scratching',
      'chicharrones',
      'chicharron',
      'pork skins',
    ],
  },
  { name: 'sesame sticks', fdc: 168856, aliases: ['sesame stick'] },
  {
    name: 'onion rings',
    fdc: 170415,
    aliases: ['onion ring', 'frozen onion rings'],
    serving: 'large',
  },
  {
    name: 'egg roll',
    fdc: 172105,
    aliases: ['spring roll', 'vegetable egg roll', 'veggie spring roll'],
  },
  { name: 'taco', fdc: 170689, aliases: ['beef taco', 'hard shell beef taco'] },
  { name: 'soft taco', fdc: 170763, aliases: ['beef soft taco'] },
  { name: 'chicken taco', fdc: 170764, aliases: ['soft chicken taco'] },
  {
    name: 'hamburger',
    fdc: 170693,
    aliases: ['burger', 'beef burger', 'plain hamburger'],
  },
  { name: 'potato salad', fdc: 169269, serving: 'cup' },

  // Drinks
  {
    name: 'water',
    fdc: 173647,
    aliases: ['tap water', 'drinking water', 'still water', 'bottled water'],
    portions: { cup: 237 },
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'sparkling water',
    fdc: 174842,
    aliases: [
      'club soda',
      'soda water',
      'seltzer',
      'seltzer water',
      'carbonated water',
      'mineral water',
      'fizzy water',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'tonic water',
    fdc: 171869,
    aliases: ['tonic'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'coffee',
    fdc: 171890,
    aliases: [
      'black coffee',
      'brewed coffee',
      'drip coffee',
      'filter coffee',
      'americano',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'espresso',
    fdc: 171891,
    aliases: ['espresso shot', 'shot of espresso'],
    portions: { piece: 30 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  {
    name: 'instant coffee',
    fdc: 174130,
    aliases: ['instant coffee prepared'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'tea',
    fdc: 173227,
    aliases: [
      'black tea',
      'brewed tea',
      'hot tea',
      'english breakfast tea',
      'earl grey',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'green tea',
    fdc: 171917,
    aliases: ['matcha tea', 'sencha'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'cola',
    fdc: 174852,
    aliases: [
      'coke',
      'coca-cola',
      'coca cola',
      'pepsi',
      'soda',
      'soft drink',
      'pop',
      'fizzy drink',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'diet cola',
    fdc: 175099,
    aliases: [
      'diet coke',
      'diet soda',
      'coke zero',
      'zero sugar cola',
      'diet pepsi',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'lemon-lime soda',
    fdc: 173205,
    aliases: ['sprite', '7up', 'seven up', 'lemon lime soda'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'ginger ale',
    fdc: 174846,
    aliases: ['ginger beer', 'canada dry'],
    serving: 'cup',
    liquid: true,
  },
  { name: 'root beer', fdc: 171871, serving: 'cup', liquid: true },
  {
    name: 'orange soda',
    fdc: 174854,
    aliases: ['fanta', 'orange fizzy drink', 'orangeade'],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'energy drink',
    fdc: 173210,
    aliases: ['red bull', 'monster energy', 'monster'],
    usdaPortions: false,
    portions: { cup: 246 },
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'sports drink',
    fdc: 173660,
    aliases: [
      'gatorade',
      'powerade',
      'electrolyte drink',
      'isotonic drink',
      'lucozade sport',
    ],
    serving: 'cup',
    liquid: true,
  },
  {
    name: 'beer',
    fdc: 168746,
    aliases: [
      'lager',
      'ale',
      'regular beer',
      'pint of beer',
      'ipa',
      'pale ale',
      'stout',
    ],
    portions: { piece: 356 },
    serving: 'piece',
    servingLabel: 'can',
    liquid: true,
  },
  {
    name: 'light beer',
    fdc: 168749,
    aliases: ['lite beer', 'bud light', 'coors light', 'miller lite'],
    portions: { piece: 354 },
    serving: 'piece',
    servingLabel: 'can',
    liquid: true,
  },
  {
    name: 'red wine',
    fdc: 173190,
    aliases: [
      'wine',
      'cabernet',
      'merlot',
      'pinot noir',
      'shiraz',
      'malbec',
      'glass of red wine',
      'glass of wine',
    ],
    portions: { piece: 147 },
    serving: 'piece',
    servingLabel: 'glass',
    liquid: true,
  },
  {
    name: 'white wine',
    fdc: 174837,
    aliases: [
      'chardonnay',
      'sauvignon blanc',
      'pinot grigio',
      'riesling',
      'glass of white wine',
      'prosecco',
      'champagne',
      'sparkling wine',
    ],
    portions: { piece: 147 },
    serving: 'piece',
    servingLabel: 'glass',
    liquid: true,
  },
  {
    name: 'dessert wine',
    fdc: 173176,
    aliases: ['port', 'sherry', 'sweet wine', 'port wine', 'moscato'],
    portions: { piece: 103 },
    serving: 'piece',
    servingLabel: 'glass',
    liquid: true,
  },
  {
    name: 'vodka',
    fdc: 174818,
    aliases: ['vodka shot', 'shot of vodka'],
    portions: { piece: 42 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  {
    name: 'whiskey',
    fdc: 174819,
    aliases: ['whisky', 'bourbon', 'scotch', 'rye whiskey', 'shot of whiskey'],
    portions: { piece: 42 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  {
    name: 'rum',
    fdc: 174817,
    aliases: ['white rum', 'dark rum', 'shot of rum'],
    portions: { piece: 42 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  {
    name: 'gin',
    fdc: 174815,
    aliases: [
      'tequila',
      'spirits',
      'liquor',
      'shot',
      'shot of gin',
      'brandy',
      'cognac',
      'mezcal',
    ],
    portions: { piece: 42 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  {
    name: 'coffee liqueur',
    fdc: 173665,
    aliases: ['kahlua', 'liqueur', 'baileys', 'irish cream'],
    portions: { piece: 52 },
    serving: 'piece',
    servingLabel: 'shot',
    liquid: true,
  },
  { name: 'horchata', fdc: 171941, serving: 'cup', liquid: true },
]

// Servings: `cup` at the rounded mean of the members' cups, `piece` 120 g for
// hand fruit, FDA reference amounts for dense snacks (nuts/seeds 30 g, dried
// fruit 40 g). Portions are the rounded mean of the members that have them.
export const CURATED_GENERICS: readonly CuratedGeneric[] = [
  {
    name: 'fruit',
    members: [
      'apple',
      'banana',
      'orange',
      'pear',
      'peach',
      'plum',
      'kiwi',
      'grape',
      'strawberry',
      'mango',
    ],
    aliases: ['piece of fruit', 'mixed fruit'],
    serving: { label: 'piece', grams: 120 },
    portions: { piece: 120, cup: 155 },
    class: 'fruit',
  },
  {
    name: 'fruit salad',
    members: [
      'pineapple',
      'grape',
      'strawberry',
      'cantaloupe',
      'apple',
      'orange',
      'kiwi',
      'banana',
    ],
    serving: { label: 'cup', grams: 170 },
    portions: { cup: 170 },
  },
  {
    name: 'berries',
    members: ['strawberry', 'blueberry', 'raspberry', 'blackberry'],
    aliases: ['mixed berries', 'berry mix'],
    serving: { label: 'cup', grams: 140 },
    portions: { cup: 140 },
    class: 'fruit',
  },
  {
    name: 'melon',
    members: ['cantaloupe', 'honeydew', 'watermelon'],
    serving: { label: 'cup', grams: 165 },
    portions: { cup: 165 },
    class: 'fruit',
  },
  {
    name: 'citrus',
    members: ['orange', 'grapefruit', 'clementine', 'tangerine'],
    aliases: ['citrus fruit'],
    serving: { label: 'piece', grams: 120 },
    portions: { piece: 120, cup: 185 },
    class: 'fruit',
  },
  {
    name: 'dried fruit',
    members: [
      'raisin',
      'dried-apricot',
      'date',
      'prune',
      'dried-fig',
      'dried-cranberry',
      'dried-mango',
    ],
    aliases: ['mixed dried fruit'],
    serving: { label: 'serving', grams: 40 },
    portions: { cup: 150 },
    class: 'dried fruit',
  },
  {
    name: 'vegetables',
    members: [
      'broccoli',
      'carrot',
      'cauliflower',
      'green-bean',
      'bell-pepper',
      'zucchini',
      'tomato',
      'cabbage',
      'pea',
    ],
    aliases: ['veggies', 'veg'],
    serving: { label: 'cup', grams: 120 },
    portions: { cup: 120 },
  },
  {
    name: 'root vegetables',
    members: ['carrot', 'potato', 'sweet-potato', 'beet', 'parsnip', 'turnip'],
    aliases: ['root veg'],
    serving: { label: 'cup', grams: 135 },
    portions: { cup: 135 },
  },
  {
    name: 'salad',
    members: [
      'romaine-lettuce',
      'iceberg-lettuce',
      'green-leaf-lettuce',
      'butter-lettuce',
      'spinach',
      'arugula',
      'kale',
    ],
    aliases: [
      'green salad',
      'side salad',
      'garden salad',
      'mixed salad',
      'leafy greens',
      'salad greens',
      'mixed greens',
    ],
    serving: { label: 'cup', grams: 40 },
    portions: { cup: 40 },
  },
  {
    name: 'nuts',
    members: [
      'almond',
      'walnut',
      'cashew',
      'peanut',
      'pistachio',
      'pecan',
      'hazelnut',
      'macadamia',
    ],
    serving: { label: 'serving', grams: 30 },
    portions: { cup: 130 },
    class: 'nuts',
  },
  {
    name: 'seeds',
    members: [
      'sunflower-seed',
      'pumpkin-seed',
      'sesame-seed',
      'flaxseed',
      'chia-seed',
      'hemp-seed',
    ],
    aliases: ['mixed seeds'],
    serving: { label: 'serving', grams: 30 },
    portions: { tbsp: 10, cup: 145 },
    class: 'seeds',
  },
  {
    name: 'nut butter',
    members: ['peanut-butter', 'almond-butter', 'cashew-butter'],
    serving: { label: 'tbsp', grams: 16 },
    portions: { tbsp: 16, cup: 255 },
  },
  {
    name: 'beans',
    members: [
      'black-bean',
      'kidney-bean',
      'pinto-bean',
      'navy-bean',
      'white-bean',
      'lima-bean',
    ],
    aliases: ['mixed beans', 'legumes', 'pulses'],
    serving: { label: 'cup', grams: 180 },
    portions: { cup: 180 },
  },
  {
    name: 'cereal',
    members: [
      'cheerios',
      'corn-flakes',
      'raisin-bran',
      'frosted-flakes',
      'shredded-wheat',
      'bran-flakes',
    ],
    aliases: ['breakfast cereal'],
    serving: { label: 'cup', grams: 40 },
    portions: { cup: 40 },
  },
  {
    name: 'fish',
    members: [
      'salmon',
      'cod',
      'tuna',
      'tilapia',
      'haddock',
      'halibut',
      'trout',
    ],
    serving: { label: 'fillet', grams: 170 },
    portions: { piece: 170 },
  },
  {
    name: 'smoothie',
    members: ['banana', 'strawberry', 'blueberry', 'yogurt'],
    aliases: ['fruit smoothie'],
    serving: { label: 'glass', grams: 250 },
    portions: { cup: 245, ml: 1.03 },
  },
  {
    name: 'juice',
    members: [
      'orange-juice',
      'apple-juice',
      'grape-juice',
      'cranberry-juice',
      'pineapple-juice',
      'grapefruit-juice',
    ],
    aliases: ['fruit juice'],
    serving: { label: 'cup', grams: 250 },
    portions: { cup: 250, ml: 1.05 },
  },
]
